// Package web serves the inbox app out of the binary.
//
// The app is a Vite build embedded at compile time, so a self-hoster runs one
// binary with no Node, no asset server, and nothing to keep in sync. The
// marketing site is deliberately not here: it is deployed separately and never
// ships to self-hosters.
package web

import (
	"embed"
	"errors"
	"io/fs"
	"net/http"
	"path"
	"strings"
)

// dist holds the built app. It is generated by `make web` and is not in source
// control, so a checkout without a build has an empty embed rather than a
// stale one.
//
//go:embed all:dist
var dist embed.FS

// ErrNotBuilt is returned when the binary was compiled without a frontend
// build. It is a real state — `go build` on a fresh checkout produces it — and
// it is worth naming rather than serving a blank page.
var ErrNotBuilt = errors.New("web: the frontend has not been built; run `make web`")

// FS returns the built app's files.
func FS() (fs.FS, error) {
	sub, err := fs.Sub(dist, "dist")
	if err != nil {
		return nil, err
	}
	if _, err := fs.Stat(sub, "index.html"); err != nil {
		return nil, ErrNotBuilt
	}
	return sub, nil
}

// Handler serves the app with a single-page fallback: anything that is not a
// real file falls through to index.html, so a deep link and a refresh both
// work.
//
// It returns ErrNotBuilt when there is nothing to serve, so a caller can decide
// whether to run API-only or refuse to start.
func Handler() (http.Handler, error) {
	files, err := FS()
	if err != nil {
		return nil, err
	}
	server := http.FileServer(http.FS(files))

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Set on every response, not only the shell. The app renders message
		// HTML inside a sandboxed iframe, and these are what stop the page
		// around it being reframed, sniffed, or used to leak a referrer.
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("X-Frame-Options", "DENY")
		w.Header().Set("Referrer-Policy", "no-referrer")

		name := strings.TrimPrefix(path.Clean(r.URL.Path), "/")
		if name == "" {
			name = "index.html"
		}

		if stat, err := fs.Stat(files, name); err != nil || stat.IsDir() {
			// Not a file we hold. Hand back the app and let the client route.
			serveIndex(w, r, files)
			return
		}

		// Hashed asset names change whenever their contents do, so they can be
		// cached indefinitely. index.html never can: it is what points at the
		// current hashes.
		if strings.HasPrefix(name, "assets/") {
			w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		} else {
			w.Header().Set("Cache-Control", "no-cache")
		}
		server.ServeHTTP(w, r)
	}), nil
}

func serveIndex(w http.ResponseWriter, r *http.Request, files fs.FS) {
	index, err := fs.ReadFile(files, "index.html")
	if err != nil {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-cache")
	http.ServeContent(w, r, "index.html", zeroTime, strings.NewReader(string(index)))
}
