/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Allocate an address
         * @description Creates a random, session-owned address on a random-pool domain.
         *
         *     Passing `kind: named` requires `local_part` and is equivalent to
         *     `POST /v1/named`, including its rate limits. The resulting inbox is
         *     public.
         */
        post: operations["createIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdentityId"];
            };
            cookie?: never;
        };
        /** Read an address */
        get: operations["getIdentity"];
        put?: never;
        post?: never;
        /**
         * Destroy an address now
         * @description Expires the identity immediately. Its messages are purged and its data
         *     key destroyed by the next purge run, after which nothing it received can
         *     be read by anyone. The address is never reallocated.
         */
        delete: operations["destroyIdentity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identities/{id}/messages": {
        parameters: {
            query?: {
                /** @description Return only what arrived after this cursor. */
                since?: components["parameters"]["Since"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                id: components["parameters"]["IdentityId"];
            };
            cookie?: never;
        };
        /** List messages after a cursor */
        get: operations["listMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identities/{id}/wait": {
        parameters: {
            query?: {
                /** @description Return only what arrived after this cursor. */
                since?: components["parameters"]["Since"];
                /** @description Seconds to hold the request open. Capped at 120. */
                timeout?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["IdentityId"];
            };
            cookie?: never;
        };
        /**
         * Long-poll for the next message
         * @description Returns immediately if anything has already arrived after `since`, and
         *     otherwise holds the request open until something does or the timeout
         *     expires.
         *
         *     The already-arrived check happens before any subscription, which is the
         *     whole point: the gap between creating an address and first waiting on it
         *     is exactly where real mail lands.
         */
        get: operations["waitForMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identities/{id}/stream": {
        parameters: {
            query?: {
                /** @description Return only what arrived after this cursor. */
                since?: components["parameters"]["Since"];
            };
            header?: never;
            path: {
                id: components["parameters"]["IdentityId"];
            };
            cookie?: never;
        };
        /**
         * Server-sent event stream for an address
         * @description Emits `message.received`, `message.parsed`, `identity.expiring`,
         *     `identity.expired` and `identity.purged`. Reconnect with the `since`
         *     cursor to collect anything missed while disconnected.
         */
        get: operations["streamIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        /** Read one message */
        get: operations["getMessage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/{id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        /**
         * Download the original MIME message
         * @description The bytes exactly as they arrived. This is the record; everything else
         *     the API returns is derived from it and can be rebuilt.
         */
        get: operations["getRawMessage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/{id}/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageId"];
                attachmentId: string;
            };
            cookie?: never;
        };
        /** Download an attachment */
        get: operations["getAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/named": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a public inbox by name
         * @description Resolves a named inbox, creating it if nobody has used the name before.
         *     The same name always resolves to the same address.
         *
         *     **Anyone who guesses the name can read this inbox.** Every interface
         *     showing one is required to say so.
         */
        post: operations["openNamedInbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/named/{address}/messages": {
        parameters: {
            query?: {
                /** @description Return only what arrived after this cursor. */
                since?: components["parameters"]["Since"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                /** @description A local part, or a full address on a public-pool domain. */
                address: components["parameters"]["NamedAddress"];
            };
            cookie?: never;
        };
        /**
         * List a public inbox's messages
         * @description No ownership check, by design. There is no owner.
         */
        get: operations["listNamedMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/named/{address}/stream": {
        parameters: {
            query?: {
                /** @description Return only what arrived after this cursor. */
                since?: components["parameters"]["Since"];
            };
            header?: never;
            path: {
                /** @description A local part, or a full address on a public-pool domain. */
                address: components["parameters"]["NamedAddress"];
            };
            cookie?: never;
        };
        /** Server-sent event stream for a public inbox */
        get: operations["streamNamedInbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/i/{signature}": {
        parameters: {
            query: {
                /** @description The remote image URL. */
                u: string;
            };
            header?: never;
            path: {
                /** @description Signature issued when the message was sanitized. */
                signature: string;
            };
            cookie?: never;
        };
        /**
         * Fetch a remote image on the reader's behalf
         * @description Message HTML never loads remote images directly: doing so would report
         *     the reader's address, user agent and read time back to the sender. This
         *     fetches them server-side instead.
         *
         *     Only URLs signed during sanitizing are served, and private address
         *     ranges are refused, including after a redirect.
         */
        get: operations["proxyImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the domains currently handing out addresses
         * @description Public information: which domains an address might land on, and which
         *     pool each belongs to. The pools never mix — `random` domains serve
         *     generated addresses and `public` domains serve shared named inboxes —
         *     because public inboxes attract far more spam and get blocklisted faster,
         *     and separating them contains the damage to the pool that earned it.
         */
        get: operations["listDomains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and readiness */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateIdentityRequest: {
            /** @description How long the address lives. Clamped to the server maximum. */
            ttl_seconds?: number;
            /**
             * @default random
             * @enum {string}
             */
            kind: "random" | "named";
            /** @description Required for `named`, ignored for `random`. */
            local_part?: string;
        };
        OpenNamedRequest: {
            /**
             * @description Lower-cased and stripped of any `+tag` before use. Must match
             *     `^[a-z0-9][a-z0-9._-]{2,63}$`, must not be a reserved name such as
             *     `postmaster`, and must not look like a generated address.
             */
            local_part: string;
        };
        Identity: {
            /** Format: uuid */
            id: string;
            address: string;
            local_part: string;
            domain: string;
            /** @enum {string} */
            kind: "random" | "named";
            /** @enum {string} */
            state: "active" | "expiring" | "expired" | "purged" | "reserved";
            /**
             * Format: int64
             * @description The sequence number of the newest message. Pass it as `since`.
             */
            cursor: number;
            /**
             * @description True for named inboxes. Anyone who guesses the name can read them,
             *     and every interface showing one must say so plainly.
             */
            public: boolean;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Absent for named inboxes, which are permanent.
             */
            expires_at?: string;
            /** @description Rolling per-message retention. Named inboxes only. */
            retention_hours?: number;
            quota: components["schemas"]["Quota"];
        };
        Quota: {
            messages: number;
            /** Format: int64 */
            bytes: number;
            used_messages: number;
            /** Format: int64 */
            used_bytes: number;
        };
        MessageList: {
            messages: components["schemas"]["MessageSummary"][];
            /**
             * Format: int64
             * @description Pass as `since` on the next call.
             */
            cursor: number;
        };
        WaitResult: components["schemas"]["MessageList"] & {
            /** @description True when the wait expired with nothing new. */
            timed_out: boolean;
        };
        MessageSummary: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            seq: number;
            subject: string;
            preview: string;
            from: components["schemas"]["Address"];
            /** Format: date-time */
            received_at: string;
            /**
             * Format: date-time
             * @description The Date header, when the message carried a usable one.
             */
            sent_at?: string;
            /** Format: int64 */
            size_bytes: number;
            /**
             * @description `received` means the message is stored but not yet parsed, so
             *     subject and preview may still be empty. `failed` means it could not
             *     be parsed; the raw message is still downloadable.
             * @enum {string}
             */
            state: "received" | "parsed" | "failed";
            attachment_count: number;
            auth: components["schemas"]["AuthResults"];
        };
        Message: components["schemas"]["MessageSummary"] & {
            to: string[];
            cc?: string[];
            text?: string;
            /**
             * @description Already sanitized, with remote images rewritten to the proxy.
             *     Render it in a sandboxed iframe with no `allow-scripts` and no
             *     `allow-same-origin`. Never inject it into the page directly.
             */
            html?: string;
            attachments: components["schemas"]["Attachment"][];
        };
        Address: {
            name?: string;
            address: string;
        };
        Attachment: {
            /** Format: uuid */
            id: string;
            filename: string;
            content_type: string;
            /** Format: int64 */
            size_bytes: number;
            /** @description False when the part was too large to store. */
            available: boolean;
        };
        /**
         * @description `none` means the check was not evaluated or the sender published
         *     nothing to check against. It is not a pass.
         */
        AuthResults: {
            spf: components["schemas"]["AuthResult"];
            dkim: components["schemas"]["AuthResult"];
            dmarc: components["schemas"]["AuthResult"];
        };
        /** @enum {string} */
        AuthResult: "none" | "pass" | "fail" | "softfail" | "neutral" | "temperror" | "permerror";
        Domain: {
            name: string;
            /**
             * @description `random` serves generated, session-owned addresses. `public` serves
             *     shared named inboxes, which anyone who guesses the name can read.
             * @enum {string}
             */
            pool: "random" | "public";
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            version?: string;
        };
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description The request was malformed or asked for something disallowed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description No such thing, or it is not yours. The two are deliberately
         *     indistinguishable.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limited. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        IdentityId: string;
        MessageId: string;
        /** @description A local part, or a full address on a public-pool domain. */
        NamedAddress: string;
        /** @description Return only what arrived after this cursor. */
        Since: number;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateIdentityRequest"];
            };
        };
        responses: {
            /** @description The address is live and already accepting mail. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            /** @description No domain in the pool can currently hand out addresses. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdentityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    destroyIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdentityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Destroyed. Repeating the call is safe. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Return only what arrived after this cursor. */
                since?: components["parameters"]["Since"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                id: components["parameters"]["IdentityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages in arrival order, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    waitForMessages: {
        parameters: {
            query?: {
                /** @description Return only what arrived after this cursor. */
                since?: components["parameters"]["Since"];
                /** @description Seconds to hold the request open. Capped at 120. */
                timeout?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["IdentityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Zero or more messages. An empty list with `timed_out: true` means
             *     nothing arrived; call again with the returned cursor.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitResult"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    streamIdentity: {
        parameters: {
            query?: {
                /** @description Return only what arrived after this cursor. */
                since?: components["parameters"]["Since"];
            };
            header?: never;
            path: {
                id: components["parameters"]["IdentityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The message. `html` is already sanitized and must still be rendered
             *     in a sandboxed iframe with no scripting: never inject it into the
             *     page directly.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRawMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The raw message. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "message/rfc822": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageId"];
                attachmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The attachment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    openNamedInbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenNamedRequest"];
            };
        };
        responses: {
            /** @description The inbox, whether it already existed or was just created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            /** @description No public-pool domain can currently hand out addresses. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listNamedMessages: {
        parameters: {
            query?: {
                /** @description Return only what arrived after this cursor. */
                since?: components["parameters"]["Since"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                /** @description A local part, or a full address on a public-pool domain. */
                address: components["parameters"]["NamedAddress"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages in arrival order, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    streamNamedInbox: {
        parameters: {
            query?: {
                /** @description Return only what arrived after this cursor. */
                since?: components["parameters"]["Since"];
            };
            header?: never;
            path: {
                /** @description A local part, or a full address on a public-pool domain. */
                address: components["parameters"]["NamedAddress"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    proxyImage: {
        parameters: {
            query: {
                /** @description The remote image URL. */
                u: string;
            };
            header?: never;
            path: {
                /** @description Signature issued when the message was sanitized. */
                signature: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            /** @description The signature does not match the URL. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The URL resolves somewhere the proxy will not go. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The remote host did not return a usable image. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDomains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The allocatable domains. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serving. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Not serving. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
