// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthResult.
const (
	Fail      AuthResult = "fail"
	Neutral   AuthResult = "neutral"
	None      AuthResult = "none"
	Pass      AuthResult = "pass"
	Permerror AuthResult = "permerror"
	Softfail  AuthResult = "softfail"
	Temperror AuthResult = "temperror"
)

// Defines values for CreateIdentityRequestKind.
const (
	CreateIdentityRequestKindNamed  CreateIdentityRequestKind = "named"
	CreateIdentityRequestKindRandom CreateIdentityRequestKind = "random"
)

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Defines values for IdentityKind.
const (
	IdentityKindNamed  IdentityKind = "named"
	IdentityKindRandom IdentityKind = "random"
)

// Defines values for IdentityState.
const (
	Active   IdentityState = "active"
	Expired  IdentityState = "expired"
	Expiring IdentityState = "expiring"
	Purged   IdentityState = "purged"
	Reserved IdentityState = "reserved"
)

// Defines values for MessageState.
const (
	MessageStateFailed   MessageState = "failed"
	MessageStateParsed   MessageState = "parsed"
	MessageStateReceived MessageState = "received"
)

// Defines values for MessageSummaryState.
const (
	MessageSummaryStateFailed   MessageSummaryState = "failed"
	MessageSummaryStateParsed   MessageSummaryState = "parsed"
	MessageSummaryStateReceived MessageSummaryState = "received"
)

// Address defines model for Address.
type Address struct {
	Address string  `json:"address"`
	Name    *string `json:"name,omitempty"`
}

// Attachment defines model for Attachment.
type Attachment struct {
	// Available False when the part was too large to store.
	Available   bool               `json:"available"`
	ContentType string             `json:"content_type"`
	Filename    string             `json:"filename"`
	Id          openapi_types.UUID `json:"id"`
	SizeBytes   int64              `json:"size_bytes"`
}

// AuthResult defines model for AuthResult.
type AuthResult string

// AuthResults `none` means the check was not evaluated or the sender published
// nothing to check against. It is not a pass.
type AuthResults struct {
	Dkim  AuthResult `json:"dkim"`
	Dmarc AuthResult `json:"dmarc"`
	Spf   AuthResult `json:"spf"`
}

// CreateIdentityRequest defines model for CreateIdentityRequest.
type CreateIdentityRequest struct {
	Kind *CreateIdentityRequestKind `json:"kind,omitempty"`

	// LocalPart Required for `named`, ignored for `random`.
	LocalPart *string `json:"local_part,omitempty"`

	// TtlSeconds How long the address lives. Clamped to the server maximum.
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// CreateIdentityRequestKind defines model for CreateIdentityRequest.Kind.
type CreateIdentityRequestKind string

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status  HealthStatus `json:"status"`
	Version *string      `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Identity defines model for Identity.
type Identity struct {
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`

	// Cursor The sequence number of the newest message. Pass it as `since`.
	Cursor int64  `json:"cursor"`
	Domain string `json:"domain"`

	// ExpiresAt Absent for named inboxes, which are permanent.
	ExpiresAt *time.Time         `json:"expires_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Kind      IdentityKind       `json:"kind"`
	LocalPart string             `json:"local_part"`

	// Public True for named inboxes. Anyone who guesses the name can read them,
	// and every interface showing one must say so plainly.
	Public bool  `json:"public"`
	Quota  Quota `json:"quota"`

	// RetentionHours Rolling per-message retention. Named inboxes only.
	RetentionHours *int          `json:"retention_hours,omitempty"`
	State          IdentityState `json:"state"`
}

// IdentityKind defines model for Identity.Kind.
type IdentityKind string

// IdentityState defines model for Identity.State.
type IdentityState string

// Message defines model for Message.
type Message struct {
	AttachmentCount int          `json:"attachment_count"`
	Attachments     []Attachment `json:"attachments"`

	// Auth `none` means the check was not evaluated or the sender published
	// nothing to check against. It is not a pass.
	Auth AuthResults `json:"auth"`
	Cc   *[]string   `json:"cc,omitempty"`
	From Address     `json:"from"`

	// Html Already sanitized, with remote images rewritten to the proxy.
	// Render it in a sandboxed iframe with no `allow-scripts` and no
	// `allow-same-origin`. Never inject it into the page directly.
	Html       *string            `json:"html,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	Preview    string             `json:"preview"`
	ReceivedAt time.Time          `json:"received_at"`

	// SentAt The Date header, when the message carried a usable one.
	SentAt    *time.Time `json:"sent_at,omitempty"`
	Seq       int64      `json:"seq"`
	SizeBytes int64      `json:"size_bytes"`

	// State `received` means the message is stored but not yet parsed, so
	// subject and preview may still be empty. `failed` means it could not
	// be parsed; the raw message is still downloadable.
	State   MessageState `json:"state"`
	Subject string       `json:"subject"`
	Text    *string      `json:"text,omitempty"`
	To      []string     `json:"to"`
}

// MessageState `received` means the message is stored but not yet parsed, so
// subject and preview may still be empty. `failed` means it could not
// be parsed; the raw message is still downloadable.
type MessageState string

// MessageList defines model for MessageList.
type MessageList struct {
	// Cursor Pass as `since` on the next call.
	Cursor   int64            `json:"cursor"`
	Messages []MessageSummary `json:"messages"`
}

// MessageSummary defines model for MessageSummary.
type MessageSummary struct {
	AttachmentCount int `json:"attachment_count"`

	// Auth `none` means the check was not evaluated or the sender published
	// nothing to check against. It is not a pass.
	Auth       AuthResults        `json:"auth"`
	From       Address            `json:"from"`
	Id         openapi_types.UUID `json:"id"`
	Preview    string             `json:"preview"`
	ReceivedAt time.Time          `json:"received_at"`

	// SentAt The Date header, when the message carried a usable one.
	SentAt    *time.Time `json:"sent_at,omitempty"`
	Seq       int64      `json:"seq"`
	SizeBytes int64      `json:"size_bytes"`

	// State `received` means the message is stored but not yet parsed, so
	// subject and preview may still be empty. `failed` means it could not
	// be parsed; the raw message is still downloadable.
	State   MessageSummaryState `json:"state"`
	Subject string              `json:"subject"`
}

// MessageSummaryState `received` means the message is stored but not yet parsed, so
// subject and preview may still be empty. `failed` means it could not
// be parsed; the raw message is still downloadable.
type MessageSummaryState string

// OpenNamedRequest defines model for OpenNamedRequest.
type OpenNamedRequest struct {
	// LocalPart Lower-cased and stripped of any `+tag` before use. Must match
	// `^[a-z0-9][a-z0-9._-]{2,63}$`, must not be a reserved name such as
	// `postmaster`, and must not look like a generated address.
	LocalPart string `json:"local_part"`
}

// Quota defines model for Quota.
type Quota struct {
	Bytes        int64 `json:"bytes"`
	Messages     int   `json:"messages"`
	UsedBytes    int64 `json:"used_bytes"`
	UsedMessages int   `json:"used_messages"`
}

// WaitResult defines model for WaitResult.
type WaitResult struct {
	// Cursor Pass as `since` on the next call.
	Cursor   int64            `json:"cursor"`
	Messages []MessageSummary `json:"messages"`

	// TimedOut True when the wait expired with nothing new.
	TimedOut bool `json:"timed_out"`
}

// IdentityId defines model for IdentityId.
type IdentityId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// MessageId defines model for MessageId.
type MessageId = openapi_types.UUID

// NamedAddress defines model for NamedAddress.
type NamedAddress = string

// Since defines model for Since.
type Since = int64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// ProxyImageParams defines parameters for ProxyImage.
type ProxyImageParams struct {
	// U The remote image URL.
	U string `form:"u" json:"u"`
}

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamIdentityParams defines parameters for StreamIdentity.
type StreamIdentityParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`
}

// WaitForMessagesParams defines parameters for WaitForMessages.
type WaitForMessagesParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`

	// Timeout Seconds to hold the request open. Capped at 120.
	Timeout *int `form:"timeout,omitempty" json:"timeout,omitempty"`
}

// ListNamedMessagesParams defines parameters for ListNamedMessages.
type ListNamedMessagesParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamNamedInboxParams defines parameters for StreamNamedInbox.
type StreamNamedInboxParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`
}

// CreateIdentityJSONRequestBody defines body for CreateIdentity for application/json ContentType.
type CreateIdentityJSONRequestBody = CreateIdentityRequest

// OpenNamedInboxJSONRequestBody defines body for OpenNamedInbox for application/json ContentType.
type OpenNamedInboxJSONRequestBody = OpenNamedRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness and readiness
	// (GET /healthz)
	Health(w http.ResponseWriter, r *http.Request)
	// Fetch a remote image on the reader's behalf
	// (GET /i/{signature})
	ProxyImage(w http.ResponseWriter, r *http.Request, signature string, params ProxyImageParams)
	// Allocate an address
	// (POST /v1/identities)
	CreateIdentity(w http.ResponseWriter, r *http.Request)
	// Destroy an address now
	// (DELETE /v1/identities/{id})
	DestroyIdentity(w http.ResponseWriter, r *http.Request, id IdentityId)
	// Read an address
	// (GET /v1/identities/{id})
	GetIdentity(w http.ResponseWriter, r *http.Request, id IdentityId)
	// List messages after a cursor
	// (GET /v1/identities/{id}/messages)
	ListMessages(w http.ResponseWriter, r *http.Request, id IdentityId, params ListMessagesParams)
	// Server-sent event stream for an address
	// (GET /v1/identities/{id}/stream)
	StreamIdentity(w http.ResponseWriter, r *http.Request, id IdentityId, params StreamIdentityParams)
	// Long-poll for the next message
	// (GET /v1/identities/{id}/wait)
	WaitForMessages(w http.ResponseWriter, r *http.Request, id IdentityId, params WaitForMessagesParams)
	// Read one message
	// (GET /v1/messages/{id})
	GetMessage(w http.ResponseWriter, r *http.Request, id MessageId)
	// Download an attachment
	// (GET /v1/messages/{id}/attachments/{attachmentId})
	GetAttachment(w http.ResponseWriter, r *http.Request, id MessageId, attachmentId openapi_types.UUID)
	// Download the original MIME message
	// (GET /v1/messages/{id}/raw)
	GetRawMessage(w http.ResponseWriter, r *http.Request, id MessageId)
	// Open a public inbox by name
	// (POST /v1/named)
	OpenNamedInbox(w http.ResponseWriter, r *http.Request)
	// List a public inbox's messages
	// (GET /v1/named/{address}/messages)
	ListNamedMessages(w http.ResponseWriter, r *http.Request, address NamedAddress, params ListNamedMessagesParams)
	// Server-sent event stream for a public inbox
	// (GET /v1/named/{address}/stream)
	StreamNamedInbox(w http.ResponseWriter, r *http.Request, address NamedAddress, params StreamNamedInboxParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Liveness and readiness
// (GET /healthz)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a remote image on the reader's behalf
// (GET /i/{signature})
func (_ Unimplemented) ProxyImage(w http.ResponseWriter, r *http.Request, signature string, params ProxyImageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Allocate an address
// (POST /v1/identities)
func (_ Unimplemented) CreateIdentity(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Destroy an address now
// (DELETE /v1/identities/{id})
func (_ Unimplemented) DestroyIdentity(w http.ResponseWriter, r *http.Request, id IdentityId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read an address
// (GET /v1/identities/{id})
func (_ Unimplemented) GetIdentity(w http.ResponseWriter, r *http.Request, id IdentityId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List messages after a cursor
// (GET /v1/identities/{id}/messages)
func (_ Unimplemented) ListMessages(w http.ResponseWriter, r *http.Request, id IdentityId, params ListMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server-sent event stream for an address
// (GET /v1/identities/{id}/stream)
func (_ Unimplemented) StreamIdentity(w http.ResponseWriter, r *http.Request, id IdentityId, params StreamIdentityParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Long-poll for the next message
// (GET /v1/identities/{id}/wait)
func (_ Unimplemented) WaitForMessages(w http.ResponseWriter, r *http.Request, id IdentityId, params WaitForMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read one message
// (GET /v1/messages/{id})
func (_ Unimplemented) GetMessage(w http.ResponseWriter, r *http.Request, id MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download an attachment
// (GET /v1/messages/{id}/attachments/{attachmentId})
func (_ Unimplemented) GetAttachment(w http.ResponseWriter, r *http.Request, id MessageId, attachmentId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download the original MIME message
// (GET /v1/messages/{id}/raw)
func (_ Unimplemented) GetRawMessage(w http.ResponseWriter, r *http.Request, id MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Open a public inbox by name
// (POST /v1/named)
func (_ Unimplemented) OpenNamedInbox(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List a public inbox's messages
// (GET /v1/named/{address}/messages)
func (_ Unimplemented) ListNamedMessages(w http.ResponseWriter, r *http.Request, address NamedAddress, params ListNamedMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server-sent event stream for a public inbox
// (GET /v1/named/{address}/stream)
func (_ Unimplemented) StreamNamedInbox(w http.ResponseWriter, r *http.Request, address NamedAddress, params StreamNamedInboxParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProxyImage operation middleware
func (siw *ServerInterfaceWrapper) ProxyImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "signature" -------------
	var signature string

	err = runtime.BindStyledParameterWithOptions("simple", "signature", chi.URLParam(r, "signature"), &signature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "signature", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ProxyImageParams

	// ------------- Required query parameter "u" -------------

	if paramValue := r.URL.Query().Get("u"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "u"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "u", r.URL.Query(), &params.U)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "u", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProxyImage(w, r, signature, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIdentity operation middleware
func (siw *ServerInterfaceWrapper) CreateIdentity(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIdentity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DestroyIdentity operation middleware
func (siw *ServerInterfaceWrapper) DestroyIdentity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DestroyIdentity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIdentity operation middleware
func (siw *ServerInterfaceWrapper) GetIdentity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIdentity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMessages operation middleware
func (siw *ServerInterfaceWrapper) ListMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMessagesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMessages(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamIdentity operation middleware
func (siw *ServerInterfaceWrapper) StreamIdentity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamIdentityParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamIdentity(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WaitForMessages operation middleware
func (siw *ServerInterfaceWrapper) WaitForMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params WaitForMessagesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "timeout" -------------

	err = runtime.BindQueryParameter("form", true, false, "timeout", r.URL.Query(), &params.Timeout)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeout", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WaitForMessages(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessage operation middleware
func (siw *ServerInterfaceWrapper) GetMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAttachment operation middleware
func (siw *ServerInterfaceWrapper) GetAttachment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", chi.URLParam(r, "attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAttachment(w, r, id, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRawMessage operation middleware
func (siw *ServerInterfaceWrapper) GetRawMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRawMessage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OpenNamedInbox operation middleware
func (siw *ServerInterfaceWrapper) OpenNamedInbox(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OpenNamedInbox(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNamedMessages operation middleware
func (siw *ServerInterfaceWrapper) ListNamedMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "address" -------------
	var address NamedAddress

	err = runtime.BindStyledParameterWithOptions("simple", "address", chi.URLParam(r, "address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNamedMessagesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNamedMessages(w, r, address, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamNamedInbox operation middleware
func (siw *ServerInterfaceWrapper) StreamNamedInbox(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "address" -------------
	var address NamedAddress

	err = runtime.BindStyledParameterWithOptions("simple", "address", chi.URLParam(r, "address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamNamedInboxParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamNamedInbox(w, r, address, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Health)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/i/{signature}", wrapper.ProxyImage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/identities", wrapper.CreateIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/identities/{id}", wrapper.DestroyIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities/{id}", wrapper.GetIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities/{id}/messages", wrapper.ListMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities/{id}/stream", wrapper.StreamIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities/{id}/wait", wrapper.WaitForMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/messages/{id}", wrapper.GetMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/messages/{id}/attachments/{attachmentId}", wrapper.GetAttachment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/messages/{id}/raw", wrapper.GetRawMessage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/named", wrapper.OpenNamedInbox)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/named/{address}/messages", wrapper.ListNamedMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/named/{address}/stream", wrapper.StreamNamedInbox)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Rbe28bt7L/KoO9BziA71pynJ6iR/0rp01bA06a46Q4wI1yI2o50rLmkhuSq7Ua+Ltf",
	"zHBfklZ+NEkL9P5la7UkhzO/eY8+JpktSmvQBJ/MPialcKLAgI4/XUg0QYXthaRPyiSzpBQhT9LEiAKT",
	"WaJkkiYOP1TKoUxmwVWYJj7LsRC0YmVdIUIyS6qK3wzbklb54JRZJ7e3aXKpChW6zT9U6Lb97pq/HG4o",
	"cSUqHZLZP87SpBA3qqiKZHZ+Rp+UiZ+edOcoE3CNjg96gd6LNX65m7wUBcpnUjr0PpLqM6fKoCwd9gy0",
	"zYSGUriQgnUgYFVpDSIuAGtAQFkttcpOS2s1SFsIZSZJOkZss+pOig8pfK1MhoekXWGonAFr9BbqXAQQ",
	"zqkNShCrgA5CrjxklfPWddTsycnzxqNyOkt71ikTvv4qGUjqbERSt3QnX1rjkdn4LyGv8EOFnlGSWRPQ",
	"8L+iLLXKBF1i+qunm3wcEPA3h6tklvzXtIf3NH7rp8+ds81Ru5x4kyO4eBjUwkMhNBGPkgXmr1HCyjrw",
	"tsCQK7MGqbzQ2tYoJwlBwIYfbGXkl6f0pQVfZTkwGYwnFUB5MDbA1lbOT4AuE2oLwiFI1GqJTgTU27lR",
	"RioflFlXyudiqXEyN0T+G2tfCLNt2O2//C2uREBgJWcG3rYI4qMHqlQ6W6ILKiJC9F/sYbwF5Bj4e0V5",
	"2+3wrsOfXf6KWaAdnoUgsrxoLr138kYoTQw7VKIfhPYIdY4GQo6s5gyhYC1o4dYIwYIP1uGktx5LazUK",
	"5n3D6Pfxm5GbrZTGI7dLyXjdb6PSxKvf8P1yG+JtDvRyxGoOucZ7dmTskbyzeTrg1CiPq5BfoWcD8TFB",
	"Q7bgbWKsoX1KwYZtJZSmXe0qNP8arIIT9F/AokQGVZqU6Ir4/7uRG/cnjdjkBZ24gAKF8Sy1LMfsmsVG",
	"eoQboSsRovbT1x6NRBettM9Rzo2x0Q4E26wVa6GMDxO46NRRAN2IVCzdg5O8VsV9ujNgFalPIVz2uCW+",
	"XD1mwZ7MaXUaCW1PHxPodw5FwDZaGNhrIaUibgv9anD1FSnLPjeuVTScnetInDDS0sEtQroHhEA5KnD2",
	"su9J/cYcXbwYG/EF77FIQa2N7R7GExaTMe0JQb/3mFkjR7D0k61BW4JCjp1T12qDfgLfaVGUKAklEUZu",
	"gw6a6GUydIhfn41q4QG/o0U9sE84/jizctxsFDEmut9g8g79+4cQ2Ht/XyF7yn9CoUN+SKMPIlR+aA7s",
	"NUEO107II7LeoPMqOqK7yW82H6Onxezj3EzGeJfvRdgxpFIEPA2KrePhGg6hDpHzhiHxoUKTIZiqWKID",
	"u2KkGKwpFGnYPoFXwnty9MLDgmMuBuq9djxNYjA5ehW8KZVD31xlL2hdejSBNYO1BZRZ2hv0KdS5ynIO",
	"Lcj+CrInO6TcyYkHeqvWIPxu7T/4OsbXIyJwFR7ecgLPzNYa8uoW1hV6j9FN0FuQCQMOhaQnRTo3wkjA",
	"DbotEN/dSmQIPrc1uQfapKh8AC+24C2UWiijt9EnHMYCHyob7g2q/s0vMdDJCytr3ucU+I2YPas1UVGi",
	"O22gBN2iCbwc3pmzgMkohkiJcCgPkQW1IQEzhIjFLZpInGXl1hhzKjZ4YwIbCzD61GYgzA7BDSpaajqt",
	"6mS7o5stK8cU/0Vv+4TWP6+S2du7Gd4seF0VhXDb5DY9MBhd5MgfVcDC3+t6+2izt/PCObFlk5HtbHTo",
	"kfbez0OhR7RYE0634IVRQf2GMoVahRwcFjYgqEKs0YPD2qkQKH6Nbqp09oYgehWjHsovKEf1wkiCigS1",
	"cqQIvJexsOBM6DSe7BdACmHs3LTPRYGn1qm1MosJvCRVAWVIGnHr9lRCp1QOs7CnIINr4824fgf7GH7t",
	"oS9YQt9Ahoeoedfj5lL5kQThmI1nw91bbcr2o32/CZAJrR9oxhvtfTi8DjB7Nwu6/Tu9ukNz2k1nx/Xg",
	"fWYrMxTV4C6iimHAwwJTzymQs/fHy435eLibKR1uFNajgHGYodo80tGTzxx1p+Tpv6eUN0ch0aV9utia",
	"5Uw4p1CCgMpT9kSe4+F+1eOHB+V1j04EB8Z/L4NqGTTMotrLKB8TXgnLKsTKBAbKjD2ZIG/nxlcMKjYV",
	"jRigIBcZlNawRMCiDNsJLCgD7A9RATJbaTIvYW6W2Oz5LZ/uRL1LAW0lbW20FbItdgxSiuYCnHjSLk3q",
	"eSTAaCi+P+RkrJFA+jU91Boo7+JrL4NuHdyBNjWqM6aZP5do2J3/vgzsrtzp0tboTjPhCZ1GAl27pKTG",
	"rkCYLSz+O4j1Apa4sg6h8jiBFxTxFCJk+dws/vetOP3t7PSf75q/k/en7z6ep18/vf3bIo3BESFkiSCg",
	"jRhioMV1LuHnZlFaHwrhA7pFykR0y7S116DVNa1eo+FKl2zTsFEvsieuwdXHGPvvNiLbZdhjNGhouw+/",
	"rTzKRykkL7hrz+OmvUXY7hY7NIzx4D9Chb5o86iYiZ3lYcBEdky+t1U4EpF35rEWKkATWrbxRiy8GKzH",
	"6mn7rr07aMyn09vKrOyI287RXEMujPRgqwBYCNWV7DkZEC1dk7mZmzc5OuSsKNQWKFL1rB9NOYAgS9eR",
	"arVCx/leIUJAR6kGnJzEBOfkZG7aFcpDZTj1IMuVgq0NmdNtU0fwlP5GKpqoF1SIqiHRB2e3KOeGWwsS",
	"hdTKYDyJ85yTExicQzmKMNullVvObWyJhk/alsRoFfzc0LIUfC5cpILzHV5BKdK1sbXvCOjzwibD6NmW",
	"CTM3hiPA3GrydmsnDK2DGpe5tdexQ2Lg2asLuMZtCkvMROWR7u0wVtaY4mDnhhcT7W0tjmXxc23Q+VyV",
	"LAGIvAXVpPu0xZCHmbXXCinC3ZxN2mM9ZLbAudEioItWRKsMjWdP2PQ+nv346vL06eTs1LpTfjG6iSY2",
	"Sp6XORbohI7gIayqoLEFVzKoYiRnkyeTM1pOvBelSmbJU36UcvuHdWaacwHlN/p/jaw5pFJclr+Qyawt",
	"sOx1Uc7Pzj5bOb85YaSe/xrdRpk190L+cfb0DzjxpQ1cT4un7nD+Um3QtGpHGZAyHBjepslUTT96tTYi",
	"VA5vB6zc3byxXvDTmxeXEPFKQYTfy5zabGUG0hIAvYWawxOHpXVhbjgs4ZDv775Vg5R8pAOxRhM6CoEM",
	"FSxFdt3XCin5msCbXPm5WWHI8liEKJoy4qlXknDrAwoZgW/0Fn65uvRAV0QJsnJMVkz/6F+yUNHFNrrq",
	"1Ibi0oa2uXHC0M3oPYerigM2ZTJdSV7OfUHy0/HqUTV2YfiKsscLYtD9UGQ+Tk928dD5wKUygpuN+x58",
	"tH3HezEAv4rnjBTbWsmDtBhr9BylMMN/ubpsVj8dX/3L1SUFKFZv0HMnsGaT1GXMUFPASZuubaMI5+M7",
	"NSjKrQ8gFUez4GIvtov/2+vsIPsHggHzv4dhm1J2OFtiLvSK2CbWficCoCx22OZ/u0/c645ByvuKXO5+",
	"nlIL35cTjvSoOzY/rkt9B6fiRVlC433o6oEtfKdG4ERsmW6eTBsX0cQoFHMeii/2O3znV9LWkZxGD73T",
	"1Y+v7HT1SU9fCe9JmxYUJ8xi6XEBDfkeFn1IGmspygN9txGaTAY5vsWrn1+/AaK562V0OqqCB9e1V5t2",
	"sOPwjb82S3sDZFNi3WxMhXebOg1r0Yd/Wbn9bKZ9vHN0ezgHcH725LMd2t3piBEZhEVabZDZL5oqmsgy",
	"LJmH5M+HlmbsxO4K08EcAy05/+f9S/b78Z/Zq941XBBxSvEQGzaCLgWFWeUcmqC3HBRzTNyFdftW6pkm",
	"BJNXMdAXdVtrNNCyd7cHmjf9qORtVDuNY4WH57FrwdT1MV1RoFQ85DCBi+BbcxUdWSxIR1UKHqQIYm6u",
	"cduHym1gzWU5fh1cZdLG38WWR5t4KLLVMXmP8ewy2l7aQ3DbIKrcAEoxgnAoGsbIMaX7PhKzo3U7WvDV",
	"ITO+by8wgSssUTA6uZ8ttOYiiFi1PvGr+2HXTbHsyrM5ZSBOMLY+JtJ0PDr9EcPxq539YQreQuaTmXJF",
	"Ir8f4AcOd+yw/pXpYO5uxC+xdkyHyf8orynrftGn91+M2TtJ/iG/WxK4feAo0tRgHdc/rSbdg5VyPnyy",
	"KOj8gcY3MWrXH3pIGPQIqaT3vh2n7R7wYhyBPCpnHxyK4miS8pzcOyzaHnFXkE37Z7GwSU863Lctu0U6",
	"N3tPKQohI9k/jpZzQdYls8ZgFmIRhkxM09GYm8honoSxWseqbpORF8p7jiKVRpDKN5uMG8DXfN2HG4mA",
	"N2GKGzThtOfU8fjyAJ7PDPBqiKs/GYavm7SMthxuzP3lUUvxRyPyGNBqESdxR2EWh0T90MeCWvUyzoXv",
	"Q6Sd+dEGIZxpzsl9oquVRy79+CZniSOXXHKqTFB6OGJJOVozgEXpsa3C3DRDC23RrT35tD05DmPloizR",
	"+LYoLcwWfLXsbtVOMcRS0NzUudUU6ygTZnzcWpSwxFAjmlhf4+TX7NTz2HZxgTI2+kGFuaFQ/UZkgQdq",
	"kZNooTleBC2M9GO4/49Q4Qfr/giDPajkjijE/6CzxPCCeNZicwKkJ0UZtqDJzrL+L7q66gwo2Wr6M/1Y",
	"XCOOb2MgwrNxveWIqS4JK84WxxnUT/IA1qxPS6s161oXybVTS3+qD9gvlPEYGVlLroDua8EEvhPcXREB",
	"npyfHct3G30Yn7x+OpyQf3J+34R8axVa3nQh+LE47kXH1i8dWRyL4rq5qEUeCr0gRRb7sw59n6hrKjqu",
	"qaGcm7sHGprjzHrWhO6H4wpzczCv8DkCSp4X+pyo7X/8MC7n6WDuYfqx/3BxNwQG0yuPQoHNAo67699Z",
	"9esp/vQ0p2kVs6Ef3u/ziiEd/RHKkPOf9HOUcSk7UR918MRGbv51rkuwX+zceSxCt40Th5l18tvYAorW",
	"HrXHWOx+9uqiMe/8vsTolVfOFjy+aDhnjrq4rJQerSD/iOFK1A+2Ms1Np26VfXN+/llQNRgl+HywIv7E",
	"MSih4cXFi+dfXNPjuOTRWuZVW8wWw/HHtI94yN6twFhu9FGcV1E03w1CxuhqEgMxT0/4sdC12Pq+VN42",
	"NPi7rjE/NycnD5yyJOwRZZOTE3i+O2g5N8NJS+XbKiqPXMeZyzGEdeMSF7TvFypwHsxk3O52p0mzb//M",
	"UkiUdp0jReasno0PxRvlm18/1MLDr+REmzbzX7XsefgDvEeXPUne3U/5mjr7cgvNb2ZaDW9GmG+HKjr9",
	"2Gw6Wts5oNV2DW7OdlI6RaJXa8OVx75NTu9NDsB/qXxgXP5/KxHtyubvfZV4RDyPtb47vwH9gjWifbwc",
	"1IjGaip7pu4vVFXZkeifJ0ZW59iWH2urvnJWVhl/SJPK6WSW5CGUfjadilJNyhzN9QRvRFHqsZzxkn8/",
	"LHGD2pZNTNrvMptOuWGYWx9m35x9c5bcvusYMdq+jMUMcve+xCx+bI3a8GfRXRn7kKQrnqqInbB+SadP",
	"I3kvjw6lO/IanhYFdvvu9v8CAAD//y+7NNWXPgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
