// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthResult.
const (
	Fail      AuthResult = "fail"
	Neutral   AuthResult = "neutral"
	None      AuthResult = "none"
	Pass      AuthResult = "pass"
	Permerror AuthResult = "permerror"
	Softfail  AuthResult = "softfail"
	Temperror AuthResult = "temperror"
)

// Defines values for CreateIdentityRequestKind.
const (
	CreateIdentityRequestKindNamed  CreateIdentityRequestKind = "named"
	CreateIdentityRequestKindRandom CreateIdentityRequestKind = "random"
)

// Defines values for DomainPool.
const (
	DomainPoolPublic DomainPool = "public"
	DomainPoolRandom DomainPool = "random"
)

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Defines values for IdentityKind.
const (
	Named  IdentityKind = "named"
	Random IdentityKind = "random"
)

// Defines values for IdentityState.
const (
	Active   IdentityState = "active"
	Expired  IdentityState = "expired"
	Expiring IdentityState = "expiring"
	Purged   IdentityState = "purged"
	Reserved IdentityState = "reserved"
)

// Defines values for MessageState.
const (
	MessageStateFailed   MessageState = "failed"
	MessageStateParsed   MessageState = "parsed"
	MessageStateReceived MessageState = "received"
)

// Defines values for MessageSummaryState.
const (
	MessageSummaryStateFailed   MessageSummaryState = "failed"
	MessageSummaryStateParsed   MessageSummaryState = "parsed"
	MessageSummaryStateReceived MessageSummaryState = "received"
)

// Address defines model for Address.
type Address struct {
	Address string  `json:"address"`
	Name    *string `json:"name,omitempty"`
}

// Attachment defines model for Attachment.
type Attachment struct {
	// Available False when the part was too large to store.
	Available   bool               `json:"available"`
	ContentType string             `json:"content_type"`
	Filename    string             `json:"filename"`
	Id          openapi_types.UUID `json:"id"`
	SizeBytes   int64              `json:"size_bytes"`
}

// AuthResult defines model for AuthResult.
type AuthResult string

// AuthResults `none` means the check was not evaluated or the sender published
// nothing to check against. It is not a pass.
type AuthResults struct {
	Dkim  AuthResult `json:"dkim"`
	Dmarc AuthResult `json:"dmarc"`
	Spf   AuthResult `json:"spf"`
}

// CreateIdentityRequest defines model for CreateIdentityRequest.
type CreateIdentityRequest struct {
	Kind *CreateIdentityRequestKind `json:"kind,omitempty"`

	// LocalPart Required for `named`, ignored for `random`.
	LocalPart *string `json:"local_part,omitempty"`

	// TtlSeconds How long the address lives. Clamped to the server maximum.
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// CreateIdentityRequestKind defines model for CreateIdentityRequest.Kind.
type CreateIdentityRequestKind string

// Domain defines model for Domain.
type Domain struct {
	Name string `json:"name"`

	// Pool `random` serves generated, session-owned addresses. `public` serves
	// shared named inboxes, which anyone who guesses the name can read.
	Pool DomainPool `json:"pool"`
}

// DomainPool `random` serves generated, session-owned addresses. `public` serves
// shared named inboxes, which anyone who guesses the name can read.
type DomainPool string

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status  HealthStatus `json:"status"`
	Version *string      `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Identity defines model for Identity.
type Identity struct {
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`

	// Cursor The sequence number of the newest message. Pass it as `since`.
	Cursor int64  `json:"cursor"`
	Domain string `json:"domain"`

	// ExpiresAt Absent for named inboxes, which are permanent.
	ExpiresAt *time.Time         `json:"expires_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Kind      IdentityKind       `json:"kind"`
	LocalPart string             `json:"local_part"`

	// Public True for named inboxes. Anyone who guesses the name can read them,
	// and every interface showing one must say so plainly.
	Public bool  `json:"public"`
	Quota  Quota `json:"quota"`

	// RetentionHours Rolling per-message retention. Named inboxes only.
	RetentionHours *int          `json:"retention_hours,omitempty"`
	State          IdentityState `json:"state"`
}

// IdentityKind defines model for Identity.Kind.
type IdentityKind string

// IdentityState defines model for Identity.State.
type IdentityState string

// Message defines model for Message.
type Message struct {
	AttachmentCount int          `json:"attachment_count"`
	Attachments     []Attachment `json:"attachments"`

	// Auth `none` means the check was not evaluated or the sender published
	// nothing to check against. It is not a pass.
	Auth AuthResults `json:"auth"`
	Cc   *[]string   `json:"cc,omitempty"`
	From Address     `json:"from"`

	// Html Already sanitized, with remote images rewritten to the proxy.
	// Render it in a sandboxed iframe with no `allow-scripts` and no
	// `allow-same-origin`. Never inject it into the page directly.
	Html       *string            `json:"html,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	Preview    string             `json:"preview"`
	ReceivedAt time.Time          `json:"received_at"`

	// SentAt The Date header, when the message carried a usable one.
	SentAt    *time.Time `json:"sent_at,omitempty"`
	Seq       int64      `json:"seq"`
	SizeBytes int64      `json:"size_bytes"`

	// State `received` means the message is stored but not yet parsed, so
	// subject and preview may still be empty. `failed` means it could not
	// be parsed; the raw message is still downloadable.
	State   MessageState `json:"state"`
	Subject string       `json:"subject"`
	Text    *string      `json:"text,omitempty"`
	To      []string     `json:"to"`
}

// MessageState `received` means the message is stored but not yet parsed, so
// subject and preview may still be empty. `failed` means it could not
// be parsed; the raw message is still downloadable.
type MessageState string

// MessageList defines model for MessageList.
type MessageList struct {
	// Cursor Pass as `since` on the next call.
	Cursor   int64            `json:"cursor"`
	Messages []MessageSummary `json:"messages"`
}

// MessageSummary defines model for MessageSummary.
type MessageSummary struct {
	AttachmentCount int `json:"attachment_count"`

	// Auth `none` means the check was not evaluated or the sender published
	// nothing to check against. It is not a pass.
	Auth       AuthResults        `json:"auth"`
	From       Address            `json:"from"`
	Id         openapi_types.UUID `json:"id"`
	Preview    string             `json:"preview"`
	ReceivedAt time.Time          `json:"received_at"`

	// SentAt The Date header, when the message carried a usable one.
	SentAt    *time.Time `json:"sent_at,omitempty"`
	Seq       int64      `json:"seq"`
	SizeBytes int64      `json:"size_bytes"`

	// State `received` means the message is stored but not yet parsed, so
	// subject and preview may still be empty. `failed` means it could not
	// be parsed; the raw message is still downloadable.
	State   MessageSummaryState `json:"state"`
	Subject string              `json:"subject"`
}

// MessageSummaryState `received` means the message is stored but not yet parsed, so
// subject and preview may still be empty. `failed` means it could not
// be parsed; the raw message is still downloadable.
type MessageSummaryState string

// Meta defines model for Meta.
type Meta struct {
	// Domains The domains currently handing out addresses. Random-pool domains
	// are omitted when random addresses are turned off.
	Domains  []Domain `json:"domains"`
	Features struct {
		// Disposable Whether private, expiring random addresses can be created. Off
		// by default. When off, only public inboxes are offered and
		// `POST /v1/identities` without `kind: named` returns 403.
		Disposable bool `json:"disposable"`
	} `json:"features"`

	// MaxWaitSeconds The longest a `wait` request will be held open.
	MaxWaitSeconds int `json:"max_wait_seconds"`

	// PublicRetentionHours How long a public inbox keeps each message before deleting it.
	PublicRetentionHours int    `json:"public_retention_hours"`
	Version              string `json:"version"`
}

// OpenNamedRequest defines model for OpenNamedRequest.
type OpenNamedRequest struct {
	// LocalPart Lower-cased and stripped of any `+tag` before use. Must match
	// `^[a-z0-9][a-z0-9._-]{2,63}$`, must not be a reserved name such as
	// `postmaster`, and must not look like a generated address.
	LocalPart string `json:"local_part"`
}

// Quota defines model for Quota.
type Quota struct {
	Bytes        int64 `json:"bytes"`
	Messages     int   `json:"messages"`
	UsedBytes    int64 `json:"used_bytes"`
	UsedMessages int   `json:"used_messages"`
}

// WaitResult defines model for WaitResult.
type WaitResult struct {
	// Cursor Pass as `since` on the next call.
	Cursor   int64            `json:"cursor"`
	Messages []MessageSummary `json:"messages"`

	// TimedOut True when the wait expired with nothing new.
	TimedOut bool `json:"timed_out"`
}

// IdentityId defines model for IdentityId.
type IdentityId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// MessageId defines model for MessageId.
type MessageId = openapi_types.UUID

// NamedAddress defines model for NamedAddress.
type NamedAddress = string

// Since defines model for Since.
type Since = int64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// ProxyImageParams defines parameters for ProxyImage.
type ProxyImageParams struct {
	// U The remote image URL.
	U string `form:"u" json:"u"`
}

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamIdentityParams defines parameters for StreamIdentity.
type StreamIdentityParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`
}

// WaitForMessagesParams defines parameters for WaitForMessages.
type WaitForMessagesParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`

	// Timeout Seconds to hold the request open. Capped at 120.
	Timeout *int `form:"timeout,omitempty" json:"timeout,omitempty"`
}

// ListNamedMessagesParams defines parameters for ListNamedMessages.
type ListNamedMessagesParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamNamedInboxParams defines parameters for StreamNamedInbox.
type StreamNamedInboxParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`
}

// CreateIdentityJSONRequestBody defines body for CreateIdentity for application/json ContentType.
type CreateIdentityJSONRequestBody = CreateIdentityRequest

// OpenNamedInboxJSONRequestBody defines body for OpenNamedInbox for application/json ContentType.
type OpenNamedInboxJSONRequestBody = OpenNamedRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness and readiness
	// (GET /healthz)
	Health(w http.ResponseWriter, r *http.Request)
	// Fetch a remote image on the reader's behalf
	// (GET /i/{signature})
	ProxyImage(w http.ResponseWriter, r *http.Request, signature string, params ProxyImageParams)
	// List the domains currently handing out addresses
	// (GET /v1/domains)
	ListDomains(w http.ResponseWriter, r *http.Request)
	// Allocate an address
	// (POST /v1/identities)
	CreateIdentity(w http.ResponseWriter, r *http.Request)
	// Destroy an address now
	// (DELETE /v1/identities/{id})
	DestroyIdentity(w http.ResponseWriter, r *http.Request, id IdentityId)
	// Read an address
	// (GET /v1/identities/{id})
	GetIdentity(w http.ResponseWriter, r *http.Request, id IdentityId)
	// List messages after a cursor
	// (GET /v1/identities/{id}/messages)
	ListMessages(w http.ResponseWriter, r *http.Request, id IdentityId, params ListMessagesParams)
	// Server-sent event stream for an address
	// (GET /v1/identities/{id}/stream)
	StreamIdentity(w http.ResponseWriter, r *http.Request, id IdentityId, params StreamIdentityParams)
	// Long-poll for the next message
	// (GET /v1/identities/{id}/wait)
	WaitForMessages(w http.ResponseWriter, r *http.Request, id IdentityId, params WaitForMessagesParams)
	// Read one message
	// (GET /v1/messages/{id})
	GetMessage(w http.ResponseWriter, r *http.Request, id MessageId)
	// Download an attachment
	// (GET /v1/messages/{id}/attachments/{attachmentId})
	GetAttachment(w http.ResponseWriter, r *http.Request, id MessageId, attachmentId openapi_types.UUID)
	// Download the original MIME message
	// (GET /v1/messages/{id}/raw)
	GetRawMessage(w http.ResponseWriter, r *http.Request, id MessageId)
	// What this server offers
	// (GET /v1/meta)
	GetMeta(w http.ResponseWriter, r *http.Request)
	// Open a public inbox by name
	// (POST /v1/named)
	OpenNamedInbox(w http.ResponseWriter, r *http.Request)
	// List a public inbox's messages
	// (GET /v1/named/{address}/messages)
	ListNamedMessages(w http.ResponseWriter, r *http.Request, address NamedAddress, params ListNamedMessagesParams)
	// Server-sent event stream for a public inbox
	// (GET /v1/named/{address}/stream)
	StreamNamedInbox(w http.ResponseWriter, r *http.Request, address NamedAddress, params StreamNamedInboxParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Liveness and readiness
// (GET /healthz)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a remote image on the reader's behalf
// (GET /i/{signature})
func (_ Unimplemented) ProxyImage(w http.ResponseWriter, r *http.Request, signature string, params ProxyImageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List the domains currently handing out addresses
// (GET /v1/domains)
func (_ Unimplemented) ListDomains(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Allocate an address
// (POST /v1/identities)
func (_ Unimplemented) CreateIdentity(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Destroy an address now
// (DELETE /v1/identities/{id})
func (_ Unimplemented) DestroyIdentity(w http.ResponseWriter, r *http.Request, id IdentityId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read an address
// (GET /v1/identities/{id})
func (_ Unimplemented) GetIdentity(w http.ResponseWriter, r *http.Request, id IdentityId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List messages after a cursor
// (GET /v1/identities/{id}/messages)
func (_ Unimplemented) ListMessages(w http.ResponseWriter, r *http.Request, id IdentityId, params ListMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server-sent event stream for an address
// (GET /v1/identities/{id}/stream)
func (_ Unimplemented) StreamIdentity(w http.ResponseWriter, r *http.Request, id IdentityId, params StreamIdentityParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Long-poll for the next message
// (GET /v1/identities/{id}/wait)
func (_ Unimplemented) WaitForMessages(w http.ResponseWriter, r *http.Request, id IdentityId, params WaitForMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read one message
// (GET /v1/messages/{id})
func (_ Unimplemented) GetMessage(w http.ResponseWriter, r *http.Request, id MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download an attachment
// (GET /v1/messages/{id}/attachments/{attachmentId})
func (_ Unimplemented) GetAttachment(w http.ResponseWriter, r *http.Request, id MessageId, attachmentId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download the original MIME message
// (GET /v1/messages/{id}/raw)
func (_ Unimplemented) GetRawMessage(w http.ResponseWriter, r *http.Request, id MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// What this server offers
// (GET /v1/meta)
func (_ Unimplemented) GetMeta(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Open a public inbox by name
// (POST /v1/named)
func (_ Unimplemented) OpenNamedInbox(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List a public inbox's messages
// (GET /v1/named/{address}/messages)
func (_ Unimplemented) ListNamedMessages(w http.ResponseWriter, r *http.Request, address NamedAddress, params ListNamedMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server-sent event stream for a public inbox
// (GET /v1/named/{address}/stream)
func (_ Unimplemented) StreamNamedInbox(w http.ResponseWriter, r *http.Request, address NamedAddress, params StreamNamedInboxParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProxyImage operation middleware
func (siw *ServerInterfaceWrapper) ProxyImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "signature" -------------
	var signature string

	err = runtime.BindStyledParameterWithOptions("simple", "signature", chi.URLParam(r, "signature"), &signature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "signature", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ProxyImageParams

	// ------------- Required query parameter "u" -------------

	if paramValue := r.URL.Query().Get("u"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "u"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "u", r.URL.Query(), &params.U)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "u", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProxyImage(w, r, signature, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDomains operation middleware
func (siw *ServerInterfaceWrapper) ListDomains(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDomains(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIdentity operation middleware
func (siw *ServerInterfaceWrapper) CreateIdentity(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIdentity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DestroyIdentity operation middleware
func (siw *ServerInterfaceWrapper) DestroyIdentity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DestroyIdentity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIdentity operation middleware
func (siw *ServerInterfaceWrapper) GetIdentity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIdentity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMessages operation middleware
func (siw *ServerInterfaceWrapper) ListMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMessagesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMessages(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamIdentity operation middleware
func (siw *ServerInterfaceWrapper) StreamIdentity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamIdentityParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamIdentity(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WaitForMessages operation middleware
func (siw *ServerInterfaceWrapper) WaitForMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params WaitForMessagesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "timeout" -------------

	err = runtime.BindQueryParameter("form", true, false, "timeout", r.URL.Query(), &params.Timeout)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeout", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WaitForMessages(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessage operation middleware
func (siw *ServerInterfaceWrapper) GetMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAttachment operation middleware
func (siw *ServerInterfaceWrapper) GetAttachment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", chi.URLParam(r, "attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAttachment(w, r, id, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRawMessage operation middleware
func (siw *ServerInterfaceWrapper) GetRawMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRawMessage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMeta operation middleware
func (siw *ServerInterfaceWrapper) GetMeta(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMeta(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OpenNamedInbox operation middleware
func (siw *ServerInterfaceWrapper) OpenNamedInbox(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OpenNamedInbox(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNamedMessages operation middleware
func (siw *ServerInterfaceWrapper) ListNamedMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "address" -------------
	var address NamedAddress

	err = runtime.BindStyledParameterWithOptions("simple", "address", chi.URLParam(r, "address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNamedMessagesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNamedMessages(w, r, address, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamNamedInbox operation middleware
func (siw *ServerInterfaceWrapper) StreamNamedInbox(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "address" -------------
	var address NamedAddress

	err = runtime.BindStyledParameterWithOptions("simple", "address", chi.URLParam(r, "address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamNamedInboxParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamNamedInbox(w, r, address, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Health)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/i/{signature}", wrapper.ProxyImage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/domains", wrapper.ListDomains)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/identities", wrapper.CreateIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/identities/{id}", wrapper.DestroyIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities/{id}", wrapper.GetIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities/{id}/messages", wrapper.ListMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities/{id}/stream", wrapper.StreamIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities/{id}/wait", wrapper.WaitForMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/messages/{id}", wrapper.GetMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/messages/{id}/attachments/{attachmentId}", wrapper.GetAttachment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/messages/{id}/raw", wrapper.GetRawMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/meta", wrapper.GetMeta)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/named", wrapper.OpenNamedInbox)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/named/{address}/messages", wrapper.ListNamedMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/named/{address}/stream", wrapper.StreamNamedInbox)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Rce48bN5L/KoW+BRbw9Ujjxy525X/OmziJAdvxjh0YuMg3orpLambYZJtkj0YxBrgP",
	"cZ/wPsmhiuyHJGoesZ0c7v7ySGq+ir+q+tWj/SkrTN0Yjdq7bPYpa4QVNXq0/OlFidpLv31R0ieps1nW",
	"CF9leaZFjdksk2WWZxY/ttJimc28bTHPXFFhLWjEytha+GyWtS0/6bcNjXLeSr3Orq/z7KWspe8n/9ii",
	"3Q6zK/5xPGGJK9Eqn83+cppntbiSdVtns0en9Enq8Olhv47UHtdoeaFX6JxY49c7yWtRY/msLC06F7bq",
	"CisbLw0t9gyUKYSCRlifg7EgYNUqBSIMAKNBQNMulSxOGmMUlKYWUk+yPLXZOOrGHR/u8K3UBR5u7Qx9",
	"azUYrbawqYQHYa28xBLEyqMFX0kHRWudsf1u9u7J8cTJezrNB9FJ7f/6JBvd1Gnipq7pTK4x2iGL8R+i",
	"PMOPLTpGSWG0R81/iqZRshB0iOkvjk7yabSBP1lcZbPsX6YDvKfhVzd9bq2JS+1K4l2FYMNisBEOaqFo",
	"81jyhbkLLGFlLDhTo6+kXkMpnVDKbLCcZAQB478zrS6//k5fG3BtUQFvg/EkPUgH2njYmta6CdBh/MaA",
	"sAglKrlEKzyq7VxLXUrnpV630lViqXAy17T9d8a8Enobxe2+/inOhEdgJWcBXncI4qVHqtRY06D1MiBC",
	"DD/sYbwDZAr8g6L83M/wocefWf6ChacZnnkviqqOh95b+VJIRQI7VKLvhHIImwo1+ApZzRlC3hhQwq4R",
	"vAHnjcXJYD2WxigULPso6PPwS+JkK6nwyOlyMl6326g8c/JXPF9ufTjNgV4mrOZYajxnv429Le9Mno8k",
	"lZRx66szdGwgPmWoyRb8nGmjaZ5GsGFbCaloVrPy8U+NrbeC/vJYN8igyrMGbR3+/pA48bBSwiYvaMUF",
	"1Ci041srKiwu+NpIj/BSqFb4oP30s0Ndog1W2lVYzrU2wQ54E8eKtZDa+Qm86NVRAJ2IVCzfg1N5Ievb",
	"dGckKlKfWtjifkNcs7rPgL07p9F52Gi3eupCv7EoPHZsYWSvRVlKkrZQb0ZHX5Gy7EvjQgbD2buOzApd",
	"Glq4Q0j/BSGwTF44e9lzUr+UowsHYyO+4DkWOci1Nv2XYYXFJKU93qtzh4XRZQJLP5gNKENQqLB36kpe",
	"opvAN0rUDZaEkgAje4kWInuZjB3iX0+TWngg72+ZHBwaqKMGgihFQgHiccOWHKxRs5Moc3DonDT6xGw0",
	"MYFwIDrMIpCUbsxcu0qQ+FicIPXSXKHLYVPJogKht0aTWTSwbnkClgA9C4XQYFGUQTMOrjgsk7jjPYRG",
	"Y8QHTEEzOJ8DSWH668KUaQHWgT7e7lt4huH5wy3tPb9vu4ad/4BC+epwj84L37qx5TQXpJ24tqI8ohaX",
	"aJ0MPvvm7cfJU/vp1Pt+Hrlg01CeC7/jc0rh8cRLvrvDMcw2D/H6jrXnY4u6QNBtvUQLZhUghRtibVHs",
	"E3gjnCNOJBwsmJ6yTt/q8vKs7FXrYFt41UiLLh5lj98vHWrPRiStCRaBXJUg07uzlRslcUfH3tnO32wo",
	"Dw1GUL/DK7AtHp5yAs/uoOn0TZ3PtdAl4CXaLZDc7UoUCK4yG/KkNEndOg9ObMEZaJSQWm2DkTikTR9b",
	"42/ln//khxjoRFik0ecVceSEhzBK0S4atCcRStAPmsDr8Zk5YJokMURKhOP7EIWXl3TBDCEScYemkk2d",
	"XWMIP9molrdbPYbBEAWOLrNHcERFt5teq/q73dHNTpQpxX812D6h1I+rbPbzzQKPA962dS3sNrvODwxG",
	"T7L5o/RYu1tZykDMB5corBVbNhnFzkSHznvv+crXCYf4TBFOt+CEll7+So5wI30FFmvjEWQt1ujA4sZK",
	"74nqB4/eWHNFED0LBJFCMQrnndAlQaUEubKkCDyXNrDgoPEkrOwWQAqhzVx334saT4yVa6kXE3hNqgJS",
	"022EqbtVCZ2ltFj4PQUZHRuv0vrtzX3ktYc+bwh9ozs8RM2HATcvpUvEUsdsPBvuwWqD0dG+X3kohFJ3",
	"NONRe+8OrwPM3iyCfv5er27QnG7S2XE9OC9Mq8dXNTqLaAMNuBuHdxwtWnN7aBHNx93dTGPxUuImCRiL",
	"BcrLezp68plJd0qe/lvhESoUJdp8iKw7s1wIayVRU2gdBZrkOe7uVx1+vFMIfO+YeWT897l2FNA44OwO",
	"I13IDZSwbH1I4qCHRljHXNzMtWsZVGwq4jVATS7SS6VgiYB147cTWFCwPCwiPRSmVWRe/FwvMc75lFe3",
	"YrO7A5qqNButjCi7vNCImscDcIxOs8Qo/QjBiDu+nXIy1uhChjED1CKUd/G1l2zoHNyBNkXVSWtm4A17",
	"ETm7TpfGY/wRitZa1F5toRK6ZNLS+nGIdMbsa5zGdXNNBNDU5DbKAObA0YZxTBF9ayneMqtVkP2dTFeM",
	"BhNeboXCtxYTSbRSusa4dC7rfYW+QguNlZfCYw4dazncM1G7JUIkEhP4cbWa6+UWYhA/gfd0VLNa5SG/",
	"HKhHT6FYKKsVEvKFLud68ebHt+9gevlwKkO0IdEt2G+SjBfEaGaBei6ImLVWO3hy+jhND/dwNjpyChG1",
	"uDrfCOmPx/gEAorxKdAQsKCHF0O+OOphhaoE06BOU8MggPNbmWifTxA7MoMLxMYBiqLqVXeJKxNyvOjp",
	"kqRPL33nGLBHTd4rxNGNJ+Q2rJQS848NaubRvy1LdFN+56XZoD0phAtoAjpe07A6gdBbWPyrF+tFJ6/W",
	"4QReUahRC19Uc734j5/Fya+nJ3//EP+dnJ98+PQo/+vj6z8t8hCVkGleIgjoqHqIcDgXL9xcLxrjfC2c",
	"R7vIeRP9MGXMBSh5QaP7REunSkn6tncto6OnBPvPLhTaFdh9XNeYNB3+2jos7+UJecBNcx7nVJ1p351i",
	"Zw8pGbwX0g+J5XsFK8xSDyMVIhDluWn9kVC45yWkAhBjuo7oh+Swxs3kdus0LJQi0/S01CuT2MW2QUY3",
	"A5EQtzUtVOKSPgSjMYHXBkTBPjGn+KMRzm2MLfmDQ982s7muhVTASQxPEYre8u7/bd6enj4uog0K5oC/",
	"wgUooUtHoQ6dP5gnYuhIdrwbH7VglAi80GaTSg5IP4F4F8ExXGDj53rFtVIbA/ON1KXZ8JSeJM9GD8vJ",
	"XM/1u0qQLl+ggzcV6gvS8FWrOEjbGBBtKVEX5KDfoGkUWwAiSN5AJBcg5tpoPDGrFVyilatY7wJk4XRu",
	"aOz2fYXS0gHUSJWfrQlhYZfkG1wrPbrEejxt2bJvFRpE603NZmGlzGY2140sLkCwoPI4PA8HJ99w0hil",
	"YPH98+Ax2S1OP8VtXE+Df2q1l2qux2wz1HfdBJ5zEmaXUTsG087pC1Py1+VcK6kvHJTosfCcCuEduRCQ",
	"Fqau6XHhKF7D0gWsWcfH80DRW7gotBjozsYA+XTHJjpmzePlQimZGeiC5OQ9WjeBZ/DgAZ/zwYO57gbI",
	"AKcdPymW5hJnEJPTy21IOC1NuU2AMOakhvwcrxPIzoMHMFqn1ZzdIhKRQ8iNL7cxq88Jc5K08B0hYunQ",
	"1CU6b82WfJEGASWKUkmNHVfcY4FCz7VpgkeE6I1zIkrQakU7oQXJSglvLKCm7RDXfzqAoUYvFnPtxNbF",
	"DGTn1UNBPxYhmHw5vpWQ3NqldppzD5VRFGetrSD7IWCDy8qYi9DGoOHZmxdwgdsclliI1iGDzWKof3FC",
	"z5swGDqrAN4Ej6dkgdrhULvInn3/5uXJ48npibEnSvgYU3UBdPZml0CSdWiCNrOZYcUjYys9MduMDcGI",
	"kcyy08nDySnNSRxNNDKbZY/5q5x7LNjoTytOvf9Kf6+RTX+QtjT6RUnsLKTm91oVHp2efrGaeVwhUTR/",
	"i/ZS6jU3HPzl9PHvsOJr4xkvYdWd63gpL1F3SktmXGpOKVzn2VROPzm51oy665EodyePJh9+ePfqZcQb",
	"hZ9uL+fW5blmUBoCkDOw4cDWYmOsDwbOcrLgz65DMdtMG1DR7xDI08JSFBdDQU6XaCfwrpJurlfoiyqk",
	"r+uoJidOluThnA/1qrn+kYKZn85eOqAjYtkZ8Zg4ZINnY6mvzGPUztFUt7e5tkJ3rs7iquVQX+pCtexc",
	"QvMNEc1w9KAvuzB8Y83V9gUJ6HYoshynD3bx0JO4pdSCO3r2KWiyR4bnYgA+CeskyjTdzUNpMBTCmWaz",
	"wH86exlHP06P/unsJTFsoy7RcbvNhi1Kn2sN0RZNujZRER6lZ4ooqozzUErOg8TAccgcdcfZQfZ3BAOW",
	"/wDDLhnZ42yJlVArEptYux0K++E63+ml+3l/c297AUnn2i4pMHbTG+GGRPSRRrBezPdrBbtBUuGgfEPp",
	"Zq/2jn1yVibgRGIh9zRKtCStQm/mw3zS6Fl0Y10WhuhS9Mu1XFee2SgYHZSNn51rTsFwsLxEYkyOHA93",
	"RtEvLtqbWl7Bf//nf/XV/34NVt+5PojWAhsaSuE7z0OqIE7zz3V0kAdZEO+tKDyshIWaQlPXiJpXWKOH",
	"pTLFhZKOaSFHlpGuOCSAccjPtoqUnbfB5EnwPXalApIDExMUnGCSSXtCMdC3fcT/Wb7tsxJXaasjFEXA",
	"nlU2SvzQHTkfjn+3XN1Ic4d8U/bhOqJ09B3F1cYlkBpaXxxZCkbPkdaJwPvsQWaw8zqSEb1P+hgE0jH1",
	"G7JqT8Eh7lE99kpvhGOuvZ8nY2V1sBgyCItuZvrtUqgQ9o3zb317TO+RpHdg+4692GFoOdrmn5l301kC",
	"vFMA2+0TioYEnf+HKbdfjMikm5GuD1tLH50+/GKL9mc6Bt4hhlAcaRJbjdVGURTYsAwpHhz71dSK/RGm",
	"o9bYwZl+7Y7NG5PWwUH24UXX/BACtLnus8K7AA2Fh42xF26yB+tI71xn0PsghjPHOjauPnn099ultd/d",
	"+oXp802tukHVu0wJaz9FV7vGaa+KsGfZngXjhyO/d2fjNf0ky+tguRSmalPPQ2NLyONEIIOsaywltwxP",
	"4IV3HS8Jsg89C8GKeAel8GKuL3A7inRjYMyVW34cbEvumYltAEaXIpO+S4mUJBmuVDFXX25j6ihYm5EW",
	"BddtMXoFLFP25tuwmR2Ds2MAnhwK49vuABM4wwZ7B8u5La6TiVVHfp/cDru+J3z3PuMqYxqjzebYlebp",
	"MPR79MePdvq72bYOMp8tlDO68tsBfsCsU4sNj0xHb7H0BHRPO6bjNHVS1kQtXg2J6K8m7J109KG8+wyp",
	"1CGPJxQYyyVyo0j3YCWt8599FcykBo2PwWjfQnSXeOcet5Lf+nR4d+UOD4YXio7es/MWRX007nhOzAYW",
	"XRthX7PPh+9C7Zu+6XHf1UcX+VzvfUv+jWOF/utgORdkXQqjNRY+lAvIxMSml7kOgua+cqNUKPzH1Fkt",
	"neNwURIPli5OkjaAb/m4dzcSHq/8FC9R+5NBUscDyQN4PtPAoyGM/mwYvo35F5pyPDEn/pKW4vdG5DGg",
	"bUR4ry0Js7NYuh75WJCr4Y4r4QZ2uPM2VkRIHtLxxldoN9Ih52hdTE6EgrRpUIfs//iFJYOue53ByxpN",
	"6+c69rV2uflu5ZNu5fBqQyWaBrXryqdCb8G1y/5U+1xvUxlFXEdqP+Pl1qKBJfoNog7p8a7oMUr7s+3i",
	"UlroBQXpOTTCK1F4fj0NOVsmVCidcAUqhfv3QvrvjP09DPao5phQiH9Ha0jgHNd32JwA6Und+C1QYB/0",
	"f9FXAGfgbdu9mDK8ZBKv42kgIvymyWA5Qk6LLiu8qReJ8ed4gL7CtIqAYSbXNbb/oT5gPyPOjQdkLblU",
	"sa8FE/hGcB+A8PDw0emxxFbUh/R7jI/H75s+fHTb+6adVehk01PwYzzuVS/Wr80sjrG4vnV+UflaLUiR",
	"xX477NDR0PedWU6eYznXN/e8xuX0ehap+2FH61wftLR+CULJLeVfErXDq8Tpe56OWmOnn4YPL26GwKjB",
	"+V4oMIXHtLv+jen9YcefH+bEbkI29OPzfdlryJOvdI8l/1kvd6dv2YrNUQdPYuQ2ld51CfaLvTsPeb+u",
	"dG2xMLZ8GorUwdqjipVUrq92vW7SQYnBK6+sqfkNF112bXgWl61UydTu9+jPxObOViaedGpXxd8ePfoi",
	"qBp1m345WHEhnDvlhYJXL149/x00PXRZJa/9/W6lPSSp8uOVC7q3nboFW8GQX6VwS0mmvBVXOhtFIy2J",
	"I2RDYqdD03CuJBb2jS5o0XmUj4ESC1lieLPfm1Dxf8qb4LLoqP+GflYorO6ybTFv5Q00bfdOg1zrtiFK",
	"UB+BGXfWflU35sUxjIW0459JsI1YSsV8fD+V9p4lcdAEsYMYL4ZEWniH6mgB4KyrU4pxyScfOC55uBVo",
	"w80nxOxbit/6BqjApyeBejv6JnRyqY3YuqEK2tWq+be+02iuHzy446tXZG24G+zBg9j40799Ndfj16+k",
	"60oGjJ/wIlbqsvtWzhc071fK5h/0i17vds6RLb/+I5Nf4bY3sWeaDHJkTXgVinbGcin3F6JNXaP0b83x",
	"/y9PdB/+Byb3TnTTfe83PS9Dd+NIQ+N7jTsqOmp9S2TzDvZqNhqtq2QT4ts8FNjIvrF1HRqY6LlJslbK",
	"uPz/lhTcvZs/D3WBxPXc19/u/B86XzEruI+Xg6xgKou2Z+r+D+XRdm70j7tGVufgk1MdM2+sKduCP+RZ",
	"a1U2yyrvGzebTkUjJ02F+mKCV6JuVCpL8JL//6USL1GZJkYhwyyz6ZSr45Vxfva307+dZtcfekEka/4h",
	"fUXu3jVYhI+jvoL+v5XqCxeHWzrjhrlQ9h2G9PqUyHRwa0m+10AyDA0XdjjuOOXp1yRS9eH6fwIAAP//",
	"lGWaoQ9MAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
