// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthResult.
const (
	Fail      AuthResult = "fail"
	Neutral   AuthResult = "neutral"
	None      AuthResult = "none"
	Pass      AuthResult = "pass"
	Permerror AuthResult = "permerror"
	Softfail  AuthResult = "softfail"
	Temperror AuthResult = "temperror"
)

// Defines values for CreateIdentityRequestKind.
const (
	CreateIdentityRequestKindNamed  CreateIdentityRequestKind = "named"
	CreateIdentityRequestKindRandom CreateIdentityRequestKind = "random"
)

// Defines values for DomainPool.
const (
	DomainPoolPublic DomainPool = "public"
	DomainPoolRandom DomainPool = "random"
)

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Defines values for IdentityKind.
const (
	Named  IdentityKind = "named"
	Random IdentityKind = "random"
)

// Defines values for IdentityState.
const (
	Active   IdentityState = "active"
	Expired  IdentityState = "expired"
	Expiring IdentityState = "expiring"
	Purged   IdentityState = "purged"
	Reserved IdentityState = "reserved"
)

// Defines values for MessageState.
const (
	MessageStateFailed   MessageState = "failed"
	MessageStateParsed   MessageState = "parsed"
	MessageStateReceived MessageState = "received"
)

// Defines values for MessageSummaryState.
const (
	MessageSummaryStateFailed   MessageSummaryState = "failed"
	MessageSummaryStateParsed   MessageSummaryState = "parsed"
	MessageSummaryStateReceived MessageSummaryState = "received"
)

// Address defines model for Address.
type Address struct {
	Address string  `json:"address"`
	Name    *string `json:"name,omitempty"`
}

// Attachment defines model for Attachment.
type Attachment struct {
	// Available False when the part was too large to store.
	Available   bool               `json:"available"`
	ContentType string             `json:"content_type"`
	Filename    string             `json:"filename"`
	Id          openapi_types.UUID `json:"id"`
	SizeBytes   int64              `json:"size_bytes"`
}

// AuthResult defines model for AuthResult.
type AuthResult string

// AuthResults `none` means the check was not evaluated or the sender published
// nothing to check against. It is not a pass.
type AuthResults struct {
	Dkim  AuthResult `json:"dkim"`
	Dmarc AuthResult `json:"dmarc"`
	Spf   AuthResult `json:"spf"`
}

// CreateIdentityRequest defines model for CreateIdentityRequest.
type CreateIdentityRequest struct {
	Kind *CreateIdentityRequestKind `json:"kind,omitempty"`

	// LocalPart Required for `named`, ignored for `random`.
	LocalPart *string `json:"local_part,omitempty"`

	// TtlSeconds How long the address lives. Clamped to the server maximum.
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// CreateIdentityRequestKind defines model for CreateIdentityRequest.Kind.
type CreateIdentityRequestKind string

// Domain defines model for Domain.
type Domain struct {
	Name string `json:"name"`

	// Pool `random` serves generated, session-owned addresses. `public` serves
	// shared named inboxes, which anyone who guesses the name can read.
	Pool DomainPool `json:"pool"`
}

// DomainPool `random` serves generated, session-owned addresses. `public` serves
// shared named inboxes, which anyone who guesses the name can read.
type DomainPool string

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status  HealthStatus `json:"status"`
	Version *string      `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Identity defines model for Identity.
type Identity struct {
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`

	// Cursor The sequence number of the newest message. Pass it as `since`.
	Cursor int64  `json:"cursor"`
	Domain string `json:"domain"`

	// ExpiresAt Absent for named inboxes, which are permanent.
	ExpiresAt *time.Time         `json:"expires_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Kind      IdentityKind       `json:"kind"`
	LocalPart string             `json:"local_part"`

	// Public True for named inboxes. Anyone who guesses the name can read them,
	// and every interface showing one must say so plainly.
	Public bool  `json:"public"`
	Quota  Quota `json:"quota"`

	// RetentionHours Rolling per-message retention. Named inboxes only.
	RetentionHours *int          `json:"retention_hours,omitempty"`
	State          IdentityState `json:"state"`
}

// IdentityKind defines model for Identity.Kind.
type IdentityKind string

// IdentityState defines model for Identity.State.
type IdentityState string

// Message defines model for Message.
type Message struct {
	AttachmentCount int          `json:"attachment_count"`
	Attachments     []Attachment `json:"attachments"`

	// Auth `none` means the check was not evaluated or the sender published
	// nothing to check against. It is not a pass.
	Auth AuthResults `json:"auth"`
	Cc   *[]string   `json:"cc,omitempty"`
	From Address     `json:"from"`

	// Html Already sanitized, with remote images rewritten to the proxy.
	// Render it in a sandboxed iframe with no `allow-scripts` and no
	// `allow-same-origin`. Never inject it into the page directly.
	Html       *string            `json:"html,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	Preview    string             `json:"preview"`
	ReceivedAt time.Time          `json:"received_at"`

	// SentAt The Date header, when the message carried a usable one.
	SentAt    *time.Time `json:"sent_at,omitempty"`
	Seq       int64      `json:"seq"`
	SizeBytes int64      `json:"size_bytes"`

	// State `received` means the message is stored but not yet parsed, so
	// subject and preview may still be empty. `failed` means it could not
	// be parsed; the raw message is still downloadable.
	State   MessageState `json:"state"`
	Subject string       `json:"subject"`
	Text    *string      `json:"text,omitempty"`
	To      []string     `json:"to"`
}

// MessageState `received` means the message is stored but not yet parsed, so
// subject and preview may still be empty. `failed` means it could not
// be parsed; the raw message is still downloadable.
type MessageState string

// MessageList defines model for MessageList.
type MessageList struct {
	// Cursor Pass as `since` on the next call.
	Cursor   int64            `json:"cursor"`
	Messages []MessageSummary `json:"messages"`
}

// MessageSummary defines model for MessageSummary.
type MessageSummary struct {
	AttachmentCount int `json:"attachment_count"`

	// Auth `none` means the check was not evaluated or the sender published
	// nothing to check against. It is not a pass.
	Auth       AuthResults        `json:"auth"`
	From       Address            `json:"from"`
	Id         openapi_types.UUID `json:"id"`
	Preview    string             `json:"preview"`
	ReceivedAt time.Time          `json:"received_at"`

	// SentAt The Date header, when the message carried a usable one.
	SentAt    *time.Time `json:"sent_at,omitempty"`
	Seq       int64      `json:"seq"`
	SizeBytes int64      `json:"size_bytes"`

	// State `received` means the message is stored but not yet parsed, so
	// subject and preview may still be empty. `failed` means it could not
	// be parsed; the raw message is still downloadable.
	State   MessageSummaryState `json:"state"`
	Subject string              `json:"subject"`
}

// MessageSummaryState `received` means the message is stored but not yet parsed, so
// subject and preview may still be empty. `failed` means it could not
// be parsed; the raw message is still downloadable.
type MessageSummaryState string

// OpenNamedRequest defines model for OpenNamedRequest.
type OpenNamedRequest struct {
	// LocalPart Lower-cased and stripped of any `+tag` before use. Must match
	// `^[a-z0-9][a-z0-9._-]{2,63}$`, must not be a reserved name such as
	// `postmaster`, and must not look like a generated address.
	LocalPart string `json:"local_part"`
}

// Quota defines model for Quota.
type Quota struct {
	Bytes        int64 `json:"bytes"`
	Messages     int   `json:"messages"`
	UsedBytes    int64 `json:"used_bytes"`
	UsedMessages int   `json:"used_messages"`
}

// WaitResult defines model for WaitResult.
type WaitResult struct {
	// Cursor Pass as `since` on the next call.
	Cursor   int64            `json:"cursor"`
	Messages []MessageSummary `json:"messages"`

	// TimedOut True when the wait expired with nothing new.
	TimedOut bool `json:"timed_out"`
}

// IdentityId defines model for IdentityId.
type IdentityId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// MessageId defines model for MessageId.
type MessageId = openapi_types.UUID

// NamedAddress defines model for NamedAddress.
type NamedAddress = string

// Since defines model for Since.
type Since = int64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// ProxyImageParams defines parameters for ProxyImage.
type ProxyImageParams struct {
	// U The remote image URL.
	U string `form:"u" json:"u"`
}

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamIdentityParams defines parameters for StreamIdentity.
type StreamIdentityParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`
}

// WaitForMessagesParams defines parameters for WaitForMessages.
type WaitForMessagesParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`

	// Timeout Seconds to hold the request open. Capped at 120.
	Timeout *int `form:"timeout,omitempty" json:"timeout,omitempty"`
}

// ListNamedMessagesParams defines parameters for ListNamedMessages.
type ListNamedMessagesParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamNamedInboxParams defines parameters for StreamNamedInbox.
type StreamNamedInboxParams struct {
	// Since Return only what arrived after this cursor.
	Since *Since `form:"since,omitempty" json:"since,omitempty"`
}

// CreateIdentityJSONRequestBody defines body for CreateIdentity for application/json ContentType.
type CreateIdentityJSONRequestBody = CreateIdentityRequest

// OpenNamedInboxJSONRequestBody defines body for OpenNamedInbox for application/json ContentType.
type OpenNamedInboxJSONRequestBody = OpenNamedRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness and readiness
	// (GET /healthz)
	Health(w http.ResponseWriter, r *http.Request)
	// Fetch a remote image on the reader's behalf
	// (GET /i/{signature})
	ProxyImage(w http.ResponseWriter, r *http.Request, signature string, params ProxyImageParams)
	// List the domains currently handing out addresses
	// (GET /v1/domains)
	ListDomains(w http.ResponseWriter, r *http.Request)
	// Allocate an address
	// (POST /v1/identities)
	CreateIdentity(w http.ResponseWriter, r *http.Request)
	// Destroy an address now
	// (DELETE /v1/identities/{id})
	DestroyIdentity(w http.ResponseWriter, r *http.Request, id IdentityId)
	// Read an address
	// (GET /v1/identities/{id})
	GetIdentity(w http.ResponseWriter, r *http.Request, id IdentityId)
	// List messages after a cursor
	// (GET /v1/identities/{id}/messages)
	ListMessages(w http.ResponseWriter, r *http.Request, id IdentityId, params ListMessagesParams)
	// Server-sent event stream for an address
	// (GET /v1/identities/{id}/stream)
	StreamIdentity(w http.ResponseWriter, r *http.Request, id IdentityId, params StreamIdentityParams)
	// Long-poll for the next message
	// (GET /v1/identities/{id}/wait)
	WaitForMessages(w http.ResponseWriter, r *http.Request, id IdentityId, params WaitForMessagesParams)
	// Read one message
	// (GET /v1/messages/{id})
	GetMessage(w http.ResponseWriter, r *http.Request, id MessageId)
	// Download an attachment
	// (GET /v1/messages/{id}/attachments/{attachmentId})
	GetAttachment(w http.ResponseWriter, r *http.Request, id MessageId, attachmentId openapi_types.UUID)
	// Download the original MIME message
	// (GET /v1/messages/{id}/raw)
	GetRawMessage(w http.ResponseWriter, r *http.Request, id MessageId)
	// Open a public inbox by name
	// (POST /v1/named)
	OpenNamedInbox(w http.ResponseWriter, r *http.Request)
	// List a public inbox's messages
	// (GET /v1/named/{address}/messages)
	ListNamedMessages(w http.ResponseWriter, r *http.Request, address NamedAddress, params ListNamedMessagesParams)
	// Server-sent event stream for a public inbox
	// (GET /v1/named/{address}/stream)
	StreamNamedInbox(w http.ResponseWriter, r *http.Request, address NamedAddress, params StreamNamedInboxParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Liveness and readiness
// (GET /healthz)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a remote image on the reader's behalf
// (GET /i/{signature})
func (_ Unimplemented) ProxyImage(w http.ResponseWriter, r *http.Request, signature string, params ProxyImageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List the domains currently handing out addresses
// (GET /v1/domains)
func (_ Unimplemented) ListDomains(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Allocate an address
// (POST /v1/identities)
func (_ Unimplemented) CreateIdentity(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Destroy an address now
// (DELETE /v1/identities/{id})
func (_ Unimplemented) DestroyIdentity(w http.ResponseWriter, r *http.Request, id IdentityId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read an address
// (GET /v1/identities/{id})
func (_ Unimplemented) GetIdentity(w http.ResponseWriter, r *http.Request, id IdentityId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List messages after a cursor
// (GET /v1/identities/{id}/messages)
func (_ Unimplemented) ListMessages(w http.ResponseWriter, r *http.Request, id IdentityId, params ListMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server-sent event stream for an address
// (GET /v1/identities/{id}/stream)
func (_ Unimplemented) StreamIdentity(w http.ResponseWriter, r *http.Request, id IdentityId, params StreamIdentityParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Long-poll for the next message
// (GET /v1/identities/{id}/wait)
func (_ Unimplemented) WaitForMessages(w http.ResponseWriter, r *http.Request, id IdentityId, params WaitForMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read one message
// (GET /v1/messages/{id})
func (_ Unimplemented) GetMessage(w http.ResponseWriter, r *http.Request, id MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download an attachment
// (GET /v1/messages/{id}/attachments/{attachmentId})
func (_ Unimplemented) GetAttachment(w http.ResponseWriter, r *http.Request, id MessageId, attachmentId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download the original MIME message
// (GET /v1/messages/{id}/raw)
func (_ Unimplemented) GetRawMessage(w http.ResponseWriter, r *http.Request, id MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Open a public inbox by name
// (POST /v1/named)
func (_ Unimplemented) OpenNamedInbox(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List a public inbox's messages
// (GET /v1/named/{address}/messages)
func (_ Unimplemented) ListNamedMessages(w http.ResponseWriter, r *http.Request, address NamedAddress, params ListNamedMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server-sent event stream for a public inbox
// (GET /v1/named/{address}/stream)
func (_ Unimplemented) StreamNamedInbox(w http.ResponseWriter, r *http.Request, address NamedAddress, params StreamNamedInboxParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProxyImage operation middleware
func (siw *ServerInterfaceWrapper) ProxyImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "signature" -------------
	var signature string

	err = runtime.BindStyledParameterWithOptions("simple", "signature", chi.URLParam(r, "signature"), &signature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "signature", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ProxyImageParams

	// ------------- Required query parameter "u" -------------

	if paramValue := r.URL.Query().Get("u"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "u"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "u", r.URL.Query(), &params.U)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "u", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProxyImage(w, r, signature, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDomains operation middleware
func (siw *ServerInterfaceWrapper) ListDomains(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDomains(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIdentity operation middleware
func (siw *ServerInterfaceWrapper) CreateIdentity(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIdentity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DestroyIdentity operation middleware
func (siw *ServerInterfaceWrapper) DestroyIdentity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DestroyIdentity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIdentity operation middleware
func (siw *ServerInterfaceWrapper) GetIdentity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIdentity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMessages operation middleware
func (siw *ServerInterfaceWrapper) ListMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMessagesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMessages(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamIdentity operation middleware
func (siw *ServerInterfaceWrapper) StreamIdentity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamIdentityParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamIdentity(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WaitForMessages operation middleware
func (siw *ServerInterfaceWrapper) WaitForMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdentityId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params WaitForMessagesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "timeout" -------------

	err = runtime.BindQueryParameter("form", true, false, "timeout", r.URL.Query(), &params.Timeout)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeout", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WaitForMessages(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessage operation middleware
func (siw *ServerInterfaceWrapper) GetMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAttachment operation middleware
func (siw *ServerInterfaceWrapper) GetAttachment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", chi.URLParam(r, "attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAttachment(w, r, id, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRawMessage operation middleware
func (siw *ServerInterfaceWrapper) GetRawMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRawMessage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OpenNamedInbox operation middleware
func (siw *ServerInterfaceWrapper) OpenNamedInbox(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OpenNamedInbox(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNamedMessages operation middleware
func (siw *ServerInterfaceWrapper) ListNamedMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "address" -------------
	var address NamedAddress

	err = runtime.BindStyledParameterWithOptions("simple", "address", chi.URLParam(r, "address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNamedMessagesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNamedMessages(w, r, address, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamNamedInbox operation middleware
func (siw *ServerInterfaceWrapper) StreamNamedInbox(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "address" -------------
	var address NamedAddress

	err = runtime.BindStyledParameterWithOptions("simple", "address", chi.URLParam(r, "address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamNamedInboxParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamNamedInbox(w, r, address, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Health)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/i/{signature}", wrapper.ProxyImage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/domains", wrapper.ListDomains)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/identities", wrapper.CreateIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/identities/{id}", wrapper.DestroyIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities/{id}", wrapper.GetIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities/{id}/messages", wrapper.ListMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities/{id}/stream", wrapper.StreamIdentity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identities/{id}/wait", wrapper.WaitForMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/messages/{id}", wrapper.GetMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/messages/{id}/attachments/{attachmentId}", wrapper.GetAttachment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/messages/{id}/raw", wrapper.GetRawMessage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/named", wrapper.OpenNamedInbox)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/named/{address}/messages", wrapper.ListNamedMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/named/{address}/stream", wrapper.StreamNamedInbox)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+R8624bR7L/qxTmv8AC+o9I2c4GWeaTNnESAXKilR0scEIfszlT5HTU0z3u7iHFGALO",
	"Q5wnPE9yUNU9F3KGusR2Auz5ZHE4fav+VdWvLvSHJDNlZTRq75LZh6QSVpTo0fKnixy1l353kdMnqZNZ",
	"UglfJGmiRYnJLJF5kiYW39fSYp7MvK0xTVxWYCloxMrYUvhkltQ1v+l3FY1y3kq9Tu7u0uRSltK3k7+v",
	"0e662RV/2Z8wx5WolU9mfztLk1LcyrIuk9nzM/okdfj0rF1Hao9rtLzQK3ROrPHzneRHUWJ+nucWnQtb",
	"dZmVlZeGFjsHZTKhoBLWp2AsCFjVSoEIA8BoEFDVSyWz08oYBbkphdSTJB3bbBx1746HO3wtdYbDrV2j",
	"r60Go9UOtoXwIKyVG8xBrDxa8IV0kNXWGdvu5uCeHE88ek9naSc6qf2XXyS9mzobuak7OpOrjHbIYvyH",
	"yK/xfY2OUZIZ7VHzn6KqlMwEHWL6q6OTfOht4C8WV8ks+X/TDt7T8K2bvrTWxKX2JfGmQLBhMdgKB6VQ",
	"tHnM+cLcDeawMhacKdEXUq8hl04oZbaYTxKCgPHfmVrnn3+nPxpwdVYAb4PxJD1IB9p42JnaugnQYfzW",
	"gLAIOSq5RCs8qt1cS51L56Ve19IVYqlwMte0/TfGvBJ6F8XtPv8proVHYCVnAd41COKle6pUWVOh9TIg",
	"QnRfHGC8AeQY+DtF+aWd4W2LP7P8FTNPM5x7L7KijIc+WHkjpCKBDZXoO6EcwrZADb5AVnOGkDcGlLBr",
	"BG/AeWNx0lmPpTEKBcs+Cvpd+GbkZCup8MjpUjJeD9uoNHHyN3y33PlwmoFejljNvtR4znYbB1vemzzt",
	"SWpUxrUvrtGxgfiQoCZb8EuijaZ5KsGGbSWkolnNysc/NdbeCvrLY1khgypNKrRl+PvtyIm7lUZs8oJW",
	"XECJQju+tazA7IavjfQIN0LVwgftp68d6hxtsNKuwHyutQl2wJs4VqyF1M5P4KJVRwF0IlKx9ABO+Y0s",
	"H9KdnqhIfUphs6cNcdXqKQMO7pxGp2GjzepjF/qNReGxYQs9ey3yXJK0hbrqHX1FynIojRsZDGfrOhIr",
	"dG5o4QYh7QNCYD564exl35H6jTm6cDA24gueY5GCXGvTPgwrLCZj2uO9eucwMzofwdIPZgvKEBQKbJ26",
	"kht0E/hGibLCnFASYGQ3aCGyl0nfIX55NqqFA3l/y+RgaKCOGgiiFCMKEI8btuRgjZqdRJ6CQ+ek0adm",
	"q4kJhAPRYRaBpDRj5toVgsTH4gSpl+YWXQrbQmYFCL0zmsyigXXNE7AE6F3IhAaLIg+aMbjisMzIHR8g",
	"NBojPuAYNIPzGUgKxx9nJh8XYBno48O+hWfo3h9u6eD9Q9vV7fwHFMoXwz06L3zt+pbT3JB24tqK/Iha",
	"bNA6GXz2/duPk4/tp1Hvp3nkjE1D/k74PZ+TC4+nXvLdDccw2xzi9Q1rz/sadYag63KJFswqQAq3xNqi",
	"2CdwJZwjTiQcLJiesk4/6PLSJG9Va7AtvK2kRRePcsDvlw61ZyMyrgkWgVyVINO7t5V7JfFIx97Yzt9t",
	"KIcGI6jf8ApsjcNTTuD8EZpOT8p0roXOATdod0BytyuRIbjCbMmT0iRl7Tw4sQNnoFJCarULRmJIm97X",
	"xj/IP//JLzHQibBIo98VxJFHPIRRinZRoT2NUIJ20AR+7J+ZA6bJKIZIibB/HyLzckMXzBAiETdoytnU",
	"2TWG8JONav6w1WMYdFFg7zJbBEdUNLtptaq92z3dbEQ5pvivOtsnlPpplcx+uV/gccDruiyF3SV36cBg",
	"tCSbP0qPpXuQpXTEvHOJwlqxY5OR7U00dN4H7xe+HHGI54pwugMntPTyN3KEW+kLsFgajyBLsUYHFrdW",
	"ek9UP3j0yppbguh1IIgUilE474TOCSo5yJUlReC5tIEFB42nYWW3AFIIbea6eS5KPDVWrqVeTOBHUhWQ",
	"mm4jTN2sSujMpcXMHyhI79h4O67f3jxFXgfo84bQ17vDIWredri5lG4kljpm49lwd1YbjI72/dZDJpR6",
	"pBmP2vt4eA0we78I2vlbvbpHc5pJZ8f14F1mat2/qt5ZRB1owOM4vONo0ZqHQ4toPh7vZiqLG4nbUcBY",
	"zFBunujoyWeOulPy9N8Kj1CgyNGmXWTdmOVMWCuJmkLtKNAkz/F4v+rw/aNC4CfHzD3jf8i1o4D6AWdz",
	"GOlCbiCHZe1DEgc9VMI65uJmrl3NoGJTEa8BSnKRXioFSwQsK7+bwIKC5W4R6SEztSLz4ud6iXHOr3l1",
	"K7b7O6CpcrPVyoi8yQv1qHk8AMfoNEuM0o8QjLjjhyknY40upBvTQS1CeR9fB8mGxsENtCmqzphm/lSh",
	"Znf++4LV+8LMS7NFe5oJR+jUOdCxK4r/zIoCIlj8fy/WC1jiyliE2uEEXhHjKYXPirle/Ocv4vS3s9O/",
	"v43/Tt6dvv3wPP3yxd1fFmkgR4SQJYKAhjEEosUpQeHmelEZ50vhPNpFyptohyljbkDJGxrdxntNgDfq",
	"RQ6uq3f0McH+s2Fk+wJ7igb1bffw29ph/iSF5AH3zXnctDcI259ibw9jMviXkL7Lbz2JM7GzHBImsmP5",
	"O1P7I4y8NY9bIT1EatnwjZCj0rgdSz0euvZ2oTGfTm9LvTIjbrtAfQOF0LkDU3vAUkjV5Q3AF6LZ12Su",
	"5/pNgRY5KvJbA8RUHetHzJwQZOk4uVyt0HK8Vwrv0VKoAScnIcA5OZnrZoR0UGsOPchypRASF8tdTLlw",
	"NiPsIrJekD6oRo7OW7PDfK65CpOjyJXUGFbiOOfkBHrrUIwi9G5p8h3HNqZCzSvtKhK09G6uaVgKMTey",
	"3IV4h0dQiHSjzda1G+jiwhhhdGLLhJ5rzQywMIq83doKTeNgi8vCmJtQTNJwfnUBN7hLYYmZqB3SuS2G",
	"JCTv2Ju55sG09yZtyXfx01ajdYWs+AYgyBZkDPdpir4MM2NuJBLD3ZxNmmUdZKbEuVbCow1WRMkMtcMu",
	"LZWcf391efpicnZq7Cm/GNxE5EbJy6rAEq1QATyEVekVNuBKelmM5GzybHJGw0n2opLJLHnBj1KulLHO",
	"TAtOoPxGf6+RNYdUiisYF3kyaxIsBwWn52dnn6zyEVcYKX28RruRes1lo7+dvfgDVvzReM7ZhVX3JH8p",
	"N6gbtaMISGomhndpMpXTD06utfC1xbueKPcnj9YLfnjz6hICXolEuIPIqYlWZpAbAqAzsGV6YrEy1s81",
	"0xKmfH91jRqk5CMtiDVq3+4QyFDBUmQ3XVqVgq8JvCmkm+sV+qwISYgyZlxPncwJt86HrONc/6TVDn6+",
	"vnRAR8Qc8trytkL4R3+ShQouNuqqlRvipXFvc22FppPRexZXNRM2qTNV5zycS6jkp8PRg2rsw/CKoscL",
	"EtDDUGQ5Tk/28dD6wKXUguuyhx58tNLJczEAvwjrjCTbmpuH3GAoZzBLYYH/fH0ZR78YH/3z9SURFKM2",
	"6LhoumWT1EbMsCXCSZOuTVSE5+MzRRQVxnnIJbNZsKFs3fL/5jh7yP6OYMDy72DYhJQtzpZYCLUisYm1",
	"22MAFMX2OyJ+Odzc61ZA0rmaXO5hnLIVrksnHCnnt2J+WkH/HkmFg/INjZfs60d2O1g5AicSy3TzbBoy",
	"Te6oVbjiRBMQY6D5pNGzmA6NI8lxNY61lOvCgyIlMzooG78719wPgSIrYInK6LUjx8X1bfrGRXtTylv4",
	"n//677aG067B6jvXA7KLwd61BY2992GsrEHzUxQVHGzVnC58J7y3IvOwEhZKYvauEiWvsEYPS2WyGyUd",
	"rb9iYh4ToQ4JYF6G0lEJpOy8DaY/gu+xSfiQHAKRElYzgxmzJ0Qhv40385G+7VGZk1iMGmZMRq2OUBRA",
	"eFbZKPGhO3I+HD/eSFZbi9qrHRNMThPXvrvGnuZG0iJZdyNKe88oLDFuBKmhgOla9nOkABbadMIre206",
	"5E2uhHO0twWx2VlAzgKikjlYdIFTyPhJB/TdRihybETPFlc/vX4DtOe2ONl6Eukd2LZfIvZ3WA4y+GtC",
	"IZDnC7AcA8Z+lTYaAHT+HybffTICMl4Kvhs29jw/e/bJFm3PdAx0HXlXcoMsfhFzvSLLsGIZEuvs+8Ox",
	"FdsjTHuNSTTk+d8fHnLYYPOJud993UIBp8TaW0tCocu+Zu2r1aFangfNxZ7RfrTmTT/I/C6oncKx9NjL",
	"UFvj3XWRR1liLrlraQIX3jVONdCtUDYJquQd5MKLub7BXRfQNeEfJ4/5dbA1+RZmZcETNeGxJEYRUkwh",
	"6loGhkBzhDJ2ULkelILfsRhNGuZjSvdt2Mye1u1pwRdDYXzbHGAC11hh6x04Ac6pOrFqmNsXD8OubUvb",
	"v8+4St8Ha7M9dqXpeAz1PfrjRzv7wxS8gcxHC+WarvxhgA9o4dhi3SvTXiNty54OtGPaT1GNypr84qsu",
	"CfXZhL2XihrKu9kCF7ksxUMKjOUsvVGke7CS1vmPvgqmAZ3Gx0iqrWI+hqw/4VbSB98O7bOPeDH0NB+9",
	"Z+ctivIoaX5J7h0WTSdDWzZIu2ch/U5PWtw3heVFOtcHT4mFMNFtHwfLuSDrkhmtMfMhVUgmJtbd5joI",
	"mlvbjFKh9hDzRqV0jmMdSSROujjJuAF8zcd9vJHweOunuEHtTztJHY+CBvA818CjIYz+aBi+jskDmrI/",
	"MXdBjFqKPxqRx4C2FaG1fhRmoevb9X0syFV3x4VwHUXaawiPCOEQbU7uE+1WOuQEpYuRdeih5sRorb1U",
	"/Z5pg67pqPSyRFP7uY6tNU1quFn5tFk5dFcWoqpQu6Z0IvQOXL1sT9X02oSE5VxvC6OI60jtZ7zcWlSw",
	"RL9F1CELzCkavZd1ZtvFafTQjgLSzzVR9VuRee6QR071CMV8kQNWN4b7fwnpvzP2jzDYvXrDiEL8B1pD",
	"AuegtMHmBEhPysrvgKLSoP+LNvs/A2/rpje263ON1/F1ICLc7NpZjpCQocsKPxYITeUf5QGMXp9WRinW",
	"tZbJNb11f6oPOEzncl8oWUvO0x9qwQS+EVwDFB6ePT87lpWJ+jD+U4oX/Z+8PHv+0E9eGqvQyKal4Md4",
	"3KtWrJ+bWRxjcW333qLwpVqQIovDjpyumtmWvi1nfjGf6/vbbuJyej2L1H3YVDPXg66aT0EouavtU6K2",
	"+zXT+D1Pe9050w/dh4v7IdDrsXoSCkzmcdxd/87cdLfjjw9zYkMDG/r++T7tNaSjvyrrS/6jfl82fstW",
	"bI86eBIjl6hb1yXYL7buPJRKmvKexczY/OtQqAzWHpXDUJI5v7qI5p3fzzF45ZU1JTfZao6Zgy4ua6lG",
	"85Lfo78W20dbmXjSqV1lXz1//klQ1Wt4+XSwIvmEZj2h4NXFq5efXdNDU+/RXOZ1U3IR/ex12jEesncr",
	"0IbL0cTzamLzbbtuYFeTQMQcPeHHQm3FznUFnabsxt+17SNzfXLyyF5gwh7tbHJyAi/324Hnut8PLF2T",
	"ReXfUITO4DGEtU09FzTvZ0pwDjqH7vZ7KEiz7/7MVEi47W2BxMxZPaMPxdtQfzCWq1K/khONzRD/rmnP",
	"4S9qn5z2pPtuf5sb8+zLHcTfnTQaHhvt7/oqOv0QJx3N7Qz2ato2DI52UlolRyfXmjOPXTMHvTcZLfsw",
	"Lv+vpYj27+avXZZ45Hqean33ftT9GXNEh3gZ5IjGcioHpu7fKKuyd6N/3jWyOofmkbHi/5U1eZ3xhzSp",
	"rUpmSeF95WbTqajkpCpQ30zwVpSVGosZL/k/BMhxg8pUkZN2s8ymUy4YFsb52VdnX50ld29bQYyWL0My",
	"g9y9qzALH3sl0vb/OWjT2MMtXXPvT6iEdUNafRqJe7lKnh7Uwruh4cLu3t79bwAAAP//Zd0wDWhCAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
